export const CONFIG = {

  USER_ID_KEY: "user_id",
  FORM_KEY: "form",

  URL_ROOT: "/spy",

  DISTIBUTION: {
    DEFAULT: 5,
    SPECIAL: [1]
  },

  CATEGORIES: [
    {
      name: "Postać",
      values: [
        'Harry Potter',
        'Darth Vader',
        'Sherlock Holmes',
        'James Bond',
        'Batman',
        'Superman',
        'Homer Simpson',
        'Myszka Miki',
        'Kubuś Puchatek',
        'Jan Paweł II',
        'Andrzej Duda',
        'Jarosław Kaczyński',
        'Sławomir Mentzen',
        'Robert Lewandowski',
        'Maria Skłodowska-Curie',
        'Spider-Man',
        'Hannibal Lecter',
        'Gandalf',
        'Shrek',
        'Albert Einstein',
        'Adolf Hitler',
        'Barack Obama',
        'Elon Musk',
        'Steve Jobs',
        'Donald Trump',
        'DJ Khaled',
        'Pitbull',
        'Vladimir Putin',
        'Michael Jackson',
        'Elvis Presley',
        'Pele',
        'Usain Bolt',
        'David Beckham',
        'Lionel Messi',
        'Leonardo da Vinci',
        'Isaac Newton',
        'Kleopatra',
        'Napoleon Bonaparte',
        'Mark Zuckerberg',
        'Taylor Swift',
        'Rihanna',
        'Beyonce',
        'Robert Makłowicz',
        'Justin Bieber',
        'Leonardo DiCaprio',
        'Selena Gomez',
        'Drake',
        'Kanye West',
        'Kim Kardashian',
        'Shakira',
        'Ed Sheeran',
        'Lady Gaga',
        'Eminem',
        'Brad Pitt',
        'Angelina Jolie',
        'Katy Perry',
        'Nicki Minaj',
        'Bruno Mars',
        'Cristiano Ronaldo',
        'Lionel Messi',
        'Kylian Mbappé',
        'Voldemort',
        'Optimus Prime',
        'Simba',
        'SpongeBob',
        'Scooby-Doo',
        'Fred Flintstone',
        'Yoda',
        'Jezus',
        'Mickey Mouse',
        'Hulk',
        'Aquaman',
        'Homer Simpson',
        'Sasha Grey',
        'Hermiona Granger',
        'Albus Dumbledore',
        'Anna Lewandowska',
        'Kuba Wojewódzki',
        'Krzysztof Ibisz',
        'Dorota Rabczewska (Doda)',
        'Julia Wieniawa',
        'Magda Gessler',
        'Ewa Chodakowska',
        'Patryk Vega',
        'Wojciech Szczęsny',
        'Mariusz Pudzianowski',
        'Friz',
        'Wersow',
        'Ekipa Friza',
        'PewDiePie',
        'MrBeast',
        'Logan Paul',
        'Pinokio',
        'Alicja z Krainy Czarów',
        'Kopciuszek',
        'Jaś i Małgosia',
        'Rudolf Czerwononosy',
        'Tarzan',
        'Jack Sparrow (Piraci z Karaibów)',
        'Neo (Matrix)',
        'Morpheus (Matrix)',
        'Captain America',
        'Dwayne "The Rock" Johnson',
        'Kamil Stoch',
        'Iga Świątek',
        'Popek',
        'Papież Franciszek',
        'Donald Tusk',
        'Fagata',
        'Young Leosia',
        'Kizo',
        'Adam Małysz',
        'Marcin Gortat',
        'Super Mario',
        'Pikachu',
        'Lara Croft',
        'Geralt z Rivii',
        'Steve z Minecrafta',
        'Władysław Jagiełło',
        'Mieszko I',
        'Czerwony Kapturek',
        'Tinki Winki (Teletubisie)',
        'Królewna Śnieżka',
        'Herkules',
        'Zeus',
        'Fiona',
        'Kot w butach',
        'Nemo',
      ],
      questions: [
        'Brak pytań dla kategorii Postać',
      ]
    },
    {
      name: "Miejsce",
      values: [
        'Stany Zjednoczone',
        'Kanada',
        'Wielka Brytania',
        'Niemcy',
        'Francja',
        'Włochy',
        'Hiszpania',
        'Australia',
        'Japonia',
        'Chiny',
        'Indie',
        'Brazylia',
        'Rosja',
        'Meksyk',
        'Szwajcaria',
        'Norwegia',
        'Polska',
        'Nowy Jork',
        'Londyn',
        'Paryż',
        'Rzym',
        'Madryt',
        'Tokio',
        'Berlin',
        'Amsterdam',
        'Warszawa',
        'Praga',
        'Dubaj',
        'Amazon',
        'IKEA',
        'H&M',
        'Zara',
        'Apple Store',
        'Nike',
        'Adidas',
        'Sephora',
        'Louis Vuitton',
        'Statua Wolności',
        'Wieża Eiffla',
        'Koloseum',
        'Wielki Mur Chiński',
        'Times Square',
        'Big Ben',
        'Stonehenge',
        'Wyspy Galapagos',
        'Las Vegas',
        'Hawaje',
        'Tajlandia',
        'Bali',
        'Santorini',
        'Barcelona',
        'Wenecja',
        'Fiji',
        'Antarktyda',
        'Chorwacja',
        'Meteoryt',
        'Arkadia',
        'Park Wodny Moczydło',
        'Fajka Bar Żurawia',
        'PiwPaw',
        'Stare Miasto',
        'Pałac Kultury i Nauki',
        'Łazienki Królewskie',
        'Muzeum Powstania Warszawskiego',
        'Zoo Warszawskie',
        'Centrum Nauki Kopernik',
        'Cmentarz Powązkowski',
        'Wola',
        'Hala Mirowska',
        'Stadion Narodowy',
        'Marki',
        'Ząbki',
        'Biedronka',
        'Lidl',
        'Carrefour',
        'Auchan',
        'Empik',
        'MediaMarkt',
        'RTV Euro AGD',
        'Kaufland',
        'Rossmann',
        'Allegro',
        'Decathlon',
        'Leclerc',
        'Castorama',
        'Pepco',
        'Dino',
        'Siłownia',
        'Tatry',
        'Mount Everest',
        'Piramida Cheopsa',
        'Egipt',
        'Budka z kebabem',
        'Biuro',
        'Warsaw Spire',
        'Pawilony Warszawskie',
        'Krzywa wieża w Pizie',
        'Pizzeria',
        'Akademik',
        'Wilno',
      ],
      questions: [
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zgadzasz się z poprzednią osobą?',
        'Czy zorganizowałbyś tam urodziny?',
        'Czy dzieci mogą się tam czegoś nauczyć?',
        'Czy poszedłbyś tam na randkę?',
        'Czy zorganizowałbyś tam komunię dziecka?',
        'Czy to miejsce jest ciasne?',
        'Czy jest tam się gdzie schować?',
        'Czy byłeś tam w ostatnich 3 dniach?',
        'Jak często tam chodzisz?',
        'Czy to miejsce jest blisko nas?',
        'Czy chciałbyś tam spędzić cały dzień?',
        'Czy to miejsce jest raczej głośne?',
        'Czy można tam coś kupić?',
        'Czy trzeba tam zachowywać ciszę?',
        'Czy to miejsce kojarzy się z pracą?',
        'Czy jest tam dużo ludzi?',
        'Czy można tam coś zjeść?',
        'Czy można tam robić zdjęcia?',
        'Czy trzeba płacić za wejście?',
        'Czy to miejsce jest na zewnątrz?',
        'Czy trzeba mieć specjalne ubranie, żeby tam wejść?',
        'Czy bywa tam gorąco?',
        'Czy w tym miejscu można się dobrze bawić?',
        'Czy to miejsce jest bezpieczne?',
        'Czy można tam znaleźć dzieci?',
        'Czy można tam znaleźć zwierzęta?',
        'Czy to miejsce jest popularne wśród turystów?',
        'Czy da się tam usiąść?',
        'Czy słychać tam muzykę?',
        'Czy ktoś tam pracuje w mundurze?',
        'Czy to miejsce znajduje się w budynku?',
        'Czy można tam coś zbudować?',
        'Czy to miejsce jest czyste?',
        'Czy bywa tam stresująco?',
        'Czy można tam odpocząć?',
        'Czy to miejsce ma zapach, który łatwo zapamiętać?',
        'Czy są tam jakieś zasady, których trzeba przestrzegać?',
        'Czy można tam spędzić romantyczny wieczór?',
        'Czy można tam krzyczeć?',
        'Czy to miejsce ma określone godziny otwarcia?',
        'Czy w tym miejscu pracuje więcej niż 10 osób?',
        'Czy są tam miejsca siedzące?',
        'Czy ludzie tam przychodzą z własnej woli?',
        'Czy można się tam zgubić?',
        'Czy jest tam toaleta?',
        'Czy to miejsce jest w centrum miasta?',
        'Czy w tym miejscu są schody?',
        'Czy można tam płacić kartą?',
        'Czy można tam pić alkohol?',
        'Czy są tam jakieś pojazdy?',
        'Czy trzeba tam mieć bilet?',
        'Czy to miejsce ma logo?',
        'Czy ktoś tam nosi kask?',
        'Czy jest tam klimatyzacja?',
        'Czy to miejsce ma sufit?',
        'Czy można tam rozmawiać przez telefon?',
        'Czy można tam tańczyć?',
        'Czy to miejsce ma dobre oświetlenie?',
        'Czy jest tam głośno przez cały czas?',
        'Czy można tam kogoś spotkać przypadkiem?',
        'Czy ktoś tam daje wskazówki lub prowadzi innych?',
        'Czy w tym miejscu widać niebo?',
        'Czy można tam się ubrudzić?',
        'Czy to miejsce kojarzy się z ruchem?',
        'Czy można tam coś zobaczyć przez szybę?',
        'Czy jest tam coś do jedzenia lub picia na sprzedaż?',
        'Czy ktoś tam sprząta regularnie?',
        'Czy to miejsce kojarzy się z odpoczynkiem?',
        'Czy w tym miejscu widać wodę?',
        'Czy można tam słuchać muzyki na żywo?',
        'Czy trzeba tam zachowywać powagę?',
        'Czy są tam uniformy?',
        'Czy można tam zrobić coś sportowego?',
        'Czy w tym miejscu są ekrany?',
        'Czy można tam siedzieć przez dłuższy czas?',
        'Czy są tam rzędy lub kolejki?',
        'Czy to miejsce ma wyraźny zapach jedzenia?',
        'Czy można tam coś kupić za gotówkę?',
        'Czy ktoś tam daje rozkazy?',
        'Czy to miejsce ma coś wspólnego z nauką?',
        'Czy w tym miejscu jest ciepło przez cały rok?',
        'Czy można tam spać?',
        'Czy to miejsce bywa hałaśliwe tylko czasami?',
        'Czy ktoś tam nosi garnitur?',
        'Czy można tam coś wypożyczyć?',
        'Czy w tym miejscu się klaszcze?',
        'Czy ludzie tam czekają na coś?',
        'Czy są tam fotele lub kanapy?',
        'Czy można tam zobaczyć plakaty lub napisy?',
        'Czy ktoś tam przemawia do ludzi?',
        'Czy to miejsce kojarzy się z jedzeniem?',
        'Czy są tam okna?',
        'Czy trzeba tam coś podpisać?',
        'Czy w tym miejscu łatwo się zgubić?',
        'Czy ktoś tam śpiewa?',
        'Czy można tam zobaczyć coś dużego?',
        'Czy ktoś tam jest w pośpiechu?',
        'Czy można tam usłyszeć śmiech?',
        'Czy to miejsce ma jakiś zapach charakterystyczny?',
        'Czy można tam coś kupić do jedzenia?',
        'Czy ktoś tam siedzi za ladą lub biurkiem?',
        'Czy w tym miejscu widać rośliny?',
        'Czy trzeba tam coś rezerwować wcześniej?',
        'Czy to miejsce działa w nocy?',
        'Czy są tam dźwięki maszyn?',
        'Czy ktoś tam nosi identyfikator?',
        'Czy można tam znaleźć lustra?',
        'Czy ktoś tam sprzedaje coś?',
        'Czy to miejsce kojarzy się z podróżą?',
        'Czy można tam znaleźć zegar?',
        'Czy mówi się tam w języku, który rozpoznajesz?',
        'Czy to miejsce ma dostęp do morza?',
        'Czy jedzenie tam jest ostre?',
        'Czy ludzie tam często się uśmiechają?',
        'Czy to popularny kierunek wakacyjny?',
        'Czy w tym kraju jest gorąco przez większość roku?',
        'Czy ten kraj jest znany z muzyki lub tańca?',
        'Czy tamtejsza kuchnia jest znana na całym świecie?',
        'Czy obowiązuje tam ruch lewostronny?',
        'Czy można tam pojechać samochodem z Polski?',
        'Czy to kraj europejski?',
        'Czy w tym kraju żyją dzikie zwierzęta, które można spotkać tylko tam?',
        'Czy to miejsce słynie z filmów lub seriali?',
        'Czy w tym kraju jest dużo gór?',
        'Czy waluta tego kraju jest inna niż euro?',
        'Czy w tym kraju często świeci słońce?',
        'Czy mieszkańcy tego kraju są znani z punktualności?',
        'Czy to kraj o dużej powierzchni?',
        'Czy w tym kraju pije się dużo kawy?',
        'Czy to kraj, do którego trudno się dostać?',
        'Czy ludzie tam lubią piłkę nożną?',
        'Czy kraj ten ma monarchię?',
        'Czy to kraj, w którym można zobaczyć pustynię?',
        'Czy w tym kraju używa się alfabetu innego niż łaciński?',
        'Czy ten kraj ma sąsiada, z którym ma napięte relacje?',
        'Czy ludzie tam często jedzą ryż?',
        'Czy to kraj, który organizował igrzyska olimpijskie?',
        'Czy w tym kraju produkuje się znane marki ubrań lub samochodów?',
        'Czy ludzie tam są znani z gościnności?',
        'Czy to kraj, w którym mógłbyś zamieszkać?'
      ]
    },
    {
      name: "Zwierzę",
      values: [
        'Lew',
        'Tygrys',
        'Lampart',
        'Jeleń',
        'Nosorożec',
        'Słoń',
        'Goryl',
        'Szympans',
        'Zebra',
        'Koala',
        'Kangur',
        'Panda',
        'Lama',
        'Surykatka',
        'Gepard',
        'Hiena',
        'Hipopotam',
        'Krokodyl',
        'Wieloryb',
        'Delfin',
        'Rekin',
        'Meduza',
        'Żółw',
        'Płaszczka',
        'Wiewiórka',
        'Niedźwiedź',
        'Wilk',
        'Lis',
        'Bóbr',
        'Jeż',
        'Sarna',
        'Żubr',
        'Krokodyl',
        'Baran',
        'Sowa',
        'Puchacz',
        'Orzeł',
        'Jaskółka',
        'Gołąb',
        'Papuga',
        'Kura',
        'Gęś',
        'Indyk',
        'Pies',
        'Kot',
        'Królik',
        'Chomik',
        'Żółw lądowy',
        'Świnka morska',
        'Koń',
        'Osioł',
        'Krowa',
        'Owca',
        'Koza',
        'Świnia',
        'Wół',
        'Kura',
        'Indyk',
        'Gęś',
        'Papuga',
        'Zając',
        'Niedźwiedź polarny',
        'Rysi',
        'Wydra',
        'Manat',
        'Słoń afrykański',
        'Wielbłąd',
        'Antylopa',
        'Puma',
        'Kuna',
        'Sokół',
        'Wrona',
        'Bąk',
        'Czapla',
        'Mewa',
        'Ryś',
        'Jeżozwierz',
        'Pelikany',
        'Wieloryb',
        'Narwal',
        'Foka',
        'Leniwiec',
        'Pangolin',
        'Kozica',
        'Kormoran',
        'Dzik',
        'Bóbr',
        'Lemur',
        'Maki',
        'Koczkodan',
        'Tarantula',
        'Gąsienica',
        'Motyl',
        'Ćma',
        'Mrówka',
        'Pchła',
        'Ślimak',
        'Raki',
      ],
      questions: [
        'Brak pytań dla kategorii Zwierzę',
      ]
    },
    {
      name: "Przedmiot",
      values: [
        'Laptop',
        'Telefon',
        'Telewizor',
        'Książka',
        'Długopis',
        'Ołówek',
        'Notatnik',
        'Czajnik',
        'Zegarek',
        'Kamera',
        'Słuchawki',
        'Myszka komputerowa',
        'Klawiatura',
        'Drukarka',
        'Lampka biurkowa',
        'Chlebak',
        'Mikrofalówka',
        'Kuchnia',
        'Lodówka',
        'Zmywarka',
        'Ekspres do kawy',
        'Czajnik elektryczny',
        'Toster',
        'Deska do krojenia',
        'Garnek',
        'Patelnia',
        'Szczoteczka do zębów',
        'Szczotka do włosów',
        'Ręcznik',
        'Poduszka',
        'Kołdra',
        'Zasłony',
        'Rama zdjęciowa',
        'Mopa',
        'Odkurzacz',
        'Pralka',
        'Suszarka do włosów',
        'Żelazko',
        'Wieszak',
        'Kubek',
        'Talerz',
        'Sztućce',
        'Butelka',
        'Wazon',
        'Świeczka',
        'Zapałki',
        'Papier toaletowy',
        'Ścierka',
        'Myjka do naczyń',
        'Worek na śmieci',
        'Skrzynka na narzędzia',
        'Narzędzia',
        'Wkrętarka',
        'Wiertarka',
        'Młotek',
        'Śrubokręt',
        'Kleje',
        'Szczypce',
        'Miarka',
        'Termometr',
        'Lustro',
        'Rama obrazu',
        'Kalenderz',
        'Agrafki',
        'Spinacz',
        'Koperta',
        'Zszywacz',
        'Gumki recepturki',
        'Tablica korkowa',
        'Fotel',
        'Stół',
        'Krzesło',
        'Szafa',
        'Komoda',
        'Stolik kawowy',
        'Regal',
        'Lampa stojąca',
        'Podgrzewacz do filiżanek',
        'Zestaw do herbaty',
        'Waga kuchenna',
        'Tarka',
        'Sitko',
        'Mieszadło',
        'Frytkownica',
        'Sokowirówka',
        'Grill',
        'Lodówka',
        'Wagonik',
        'Klepsydra',
        'Skrzynka na listy',
        'Skrzynia',
        'Tablica do rysowania',
        'Płytki CD',
        'Głośnik',
        'Mikrofon',
        'Lampka nocna',
        'Zegarek ścienny',
        'Torba',
        'Plecak',
        'Portfel',
      ],
      questions: [
        'Brak pytań dla kategorii Przedmiot',
      ]
    },
    {
      name: "Jedzenie",
      values: [
        'Kotlet schabowy',
        'Bigos',
        'Pierogi ruskie',
        'Zupa pomidorowa',
        'Rosół',
        'Gołąbki',
        'Barszcz czerwony',
        'Żurek',
        'Kebab',
        'Pizza Margherita',
        'Spaghetti Bolognese',
        'Lasagne',
        'Tiramisu',
        'Burger z wołowiną',
        'Frytki',
        'Hot dog',
        'Kurczak z rożna',
        'Jajecznica',
        'Omlet',
        'Kiełbasa biała',
        'Sernik',
        'Szarlotka',
        'Lody czekoladowe',
        'Pączki z marmoladą',
        'Kawa espresso',
        'Czekolada z orzechami',
        'Chleb',
        'Bagietka',
        'Rogal',
        'Croissant',
        'Baton Snickers',
        'Baton Mars',
        'Baton Twix',
        'Baton Milky Way',
        'Chipsy Lays',
        'Chipsy Pringles',
        'Orzeszki ziemne',
        'Pistacje',
        'Migdały',
        'Banan',
        'Jabłko',
        'Gruszka',
        'Pomarańcza',
        'Mandarynka',
        'Truskawka',
        'Malina',
        'Borówka amerykańska',
        'Winogrona',
        'Morela',
        'Śliwka',
        'Ananas',
        'Mango',
        'Awokado',
        'Sałatka cezar',
        'Tarta owocowa',
        'Makaron spaghetti',
        'Tortilla',
        'Burrito',
        'Quesadilla',
        'Nachos',
        'Guacamole',
        'Sushi',
        'Tatar wołowy',
        'Sznycel wiedeński',
        'Krewetki',
        'Tuńczyk w sosie własnym',
        'Tosty z szynką',
        'Jajko sadzone',
        'Ryż biały',
        'Sos sojowy',
        'Sos BBQ',
        'Sos czosnkowy',
        'Majonez',
        'Ketchup',
        'Musztarda',
        'Chrzan',
        'Hummus',
        'Baklava',
        'Kawałek tortu czekoladowego',
        'Ciasto marchewkowe',
        'Muffiny czekoladowe',
        'Rogal z dżemem',
        'Kanapka z szynką',
        'Masło orzechowe',
        'Dżem truskawkowy',
        'Nutella',
        'Miód',
        'Chałwa',
        'Beza',
        'Ciasteczka owsiane',
        'Ciasteczka czekoladowe',
        'Galaretka owocowa',
        'Kisiel truskawkowy',
        'Budyń waniliowy',
        'Pieczony ziemniak',
        'Kapusta kiszona',
        'Ogórek kiszony',
        'Marynowane grzyby',
        'Piernik',
      ],
      questions: [
        'Brak pytań dla kategorii Jedzenie',
      ]
    }
  ]
}