export const CONFIG = {

  USER_ID_KEY: "user_id",
  FORM_KEY: "form",

  URL_ROOT: "/spy",


  CATEGORIES: [
    {
      name: "Postać",
      values: [
        'Harry Potter',
        'Darth Vader',
        'Sherlock Holmes',
        'James Bond',
        'Batman',
        'Superman',
        'Homer Simpson',
        'Myszka Miki',
        'Kubuś Puchatek',
        'Jan Paweł II',
        'Andrzej Duda',
        'Jarosław Kaczyński',
        'Sławomir Mentzen',
        'Robert Lewandowski',
        'Maria Skłodowska-Curie',
        'Spider-Man',
        'Hannibal Lecter',
        'Gandalf',
        'Shrek',
        'Albert Einstein',
        'Adolf Hitler',
        'Barack Obama',
        'Elon Musk',
        'Steve Jobs',
        'Donald Trump',
        'DJ Khaled',
        'Pitbull',
        'Vladimir Putin',
        'Michael Jackson',
        'Elvis Presley',
        'Pele',
        'Usain Bolt',
        'David Beckham',
        'Lionel Messi',
        'Leonardo da Vinci',
        'Isaac Newton',
        'Kleopatra',
        'Napoleon Bonaparte',
        'Mark Zuckerberg',
        'Taylor Swift',
        'Rihanna',
        'Beyonce',
        'Robert Makłowicz',
        'Justin Bieber',
        'Leonardo DiCaprio',
        'Selena Gomez',
        'Drake',
        'Kanye West',
        'Kim Kardashian',
        'Shakira',
        'Ed Sheeran',
        'Lady Gaga',
        'Eminem',
        'Brad Pitt',
        'Angelina Jolie',
        'Katy Perry',
        'Nicki Minaj',
        'Bruno Mars',
        'Cristiano Ronaldo',
        'Lionel Messi',
        'Kylian Mbappé',
        'Voldemort',
        'Optimus Prime',
        'Simba',
        'SpongeBob',
        'Scooby-Doo',
        'Fred Flintstone',
        'Yoda',
        'Jezus',
        'Mickey Mouse',
        'Hulk',
        'Aquaman',
        'Homer Simpson',
        'Sasha Grey',
        'Hermiona Granger',
        'Albus Dumbledore',
        'Anna Lewandowska',
        'Kuba Wojewódzki',
        'Krzysztof Ibisz',
        'Dorota Rabczewska (Doda)',
        'Julia Wieniawa',
        'Magda Gessler',
        'Ewa Chodakowska',
        'Patryk Vega',
        'Wojciech Szczęsny',
        'Mariusz Pudzianowski',
        'Friz',
        'Wersow',
        'Ekipa Friza',
        'PewDiePie',
        'MrBeast',
        'Logan Paul',
        'Pinokio',
        'Alicja z Krainy Czarów',
        'Kopciuszek',
        'Jaś i Małgosia',
        'Rudolf Czerwononosy',
        'Tarzan',
        'Jack Sparrow (Piraci z Karaibów)',
        'Neo (Matrix)',
        'Morpheus (Matrix)',
        'Captain America',
        'Dwayne "The Rock" Johnson',
        'Kamil Stoch',
        'Iga Świątek',
        'Popek',
        'Papież Franciszek',
        'Donald Tusk',
        'Fagata',
        'Young Leosia',
        'Kizo',
        'Adam Małysz',
        'Marcin Gortat',
        'Super Mario',
        'Pikachu',
        'Lara Croft',
        'Geralt z Rivii',
        'Steve z Minecrafta',
        'Władysław Jagiełło',
        'Mieszko I',
        'Czerwony Kapturek',
        'Tinki Winki (Teletubisie)',
        'Królewna Śnieżka',
        'Herkules',
        'Zeus',
        'Fiona',
        'Kot w butach',
        'Nemo',
      ],
    },
    {
      name: "Miejsce",
      values: [
        'Stany Zjednoczone',
        'Kanada',
        'Wielka Brytania',
        'Niemcy',
        'Francja',
        'Włochy',
        'Hiszpania',
        'Australia',
        'Japonia',
        'Chiny',
        'Indie',
        'Brazylia',
        'Rosja',
        'Meksyk',
        'Szwajcaria',
        'Norwegia',
        'Polska',
        'Nowy Jork',
        'Londyn',
        'Paryż',
        'Rzym',
        'Madryt',
        'Tokio',
        'Berlin',
        'Amsterdam',
        'Warszawa',
        'Praga',
        'Dubaj',
        'Amazon',
        'IKEA',
        'H&M',
        'Zara',
        'Apple Store',
        'Nike',
        'Adidas',
        'Sephora',
        'Louis Vuitton',
        'Statua Wolności',
        'Wieża Eiffla',
        'Koloseum',
        'Wielki Mur Chiński',
        'Times Square',
        'Big Ben',
        'Stonehenge',
        'Wyspy Galapagos',
        'Las Vegas',
        'Hawaje',
        'Tajlandia',
        'Bali',
        'Santorini',
        'Barcelona',
        'Wenecja',
        'Fiji',
        'Antarktyda',
        'Chorwacja',
        'Meteoryt',
        'Arkadia',
        'Park Wodny Moczydło',
        'Fajka Bar Żurawia',
        'PiwPaw',
        'Stare Miasto',
        'Pałac Kultury i Nauki',
        'Łazienki Królewskie',
        'Muzeum Powstania Warszawskiego',
        'Zoo Warszawskie',
        'Centrum Nauki Kopernik',
        'Cmentarz Powązkowski',
        'Wola',
        'Hala Mirowska',
        'Stadion Narodowy',
        'Marki',
        'Ząbki',
        'Biedronka',
        'Lidl',
        'Carrefour',
        'Auchan',
        'Empik',
        'MediaMarkt',
        'RTV Euro AGD',
        'Kaufland',
        'Rossmann',
        'Allegro',
        'Decathlon',
        'Leclerc',
        'Castorama',
        'Pepco',
        'Dino',
        'Siłownia',
        'Tatry',
        'Mount Everest',
        'Piramida Cheopsa',
        'Egipt',
        'Budka z kebabem',
        'Biuro',
        'Warsaw Spire',
        'Pawilony Warszawskie',
        'Krzywa wieża w Pizie',
        'Pizzeria',
        'Akademik',
        'Wilno',
      ],
    },
    {
      name: "Zwierzę",
      values: [
        'Lew',
        'Tygrys',
        'Lampart',
        'Jeleń',
        'Nosorożec',
        'Słoń',
        'Goryl',
        'Szympans',
        'Zebra',
        'Koala',
        'Kangur',
        'Panda',
        'Lama',
        'Surykatka',
        'Gepard',
        'Hiena',
        'Hipopotam',
        'Krokodyl',
        'Wieloryb',
        'Delfin',
        'Rekin',
        'Meduza',
        'Żółw',
        'Płaszczka',
        'Skwirrel',
        'Wiewiórka',
        'Niedźwiedź',
        'Wilk',
        'Lis',
        'Bóbr',
        'Jeż',
        'Sarna',
        'Żubr',
        'Krokodyl',
        'Banan',
        'Sowa',
        'Puchacz',
        'Orzeł',
        'Jaskółka',
        'Gołąb',
        'Papuga',
        'Kura',
        'Gęś',
        'Indyk',
        'Pies',
        'Kot',
        'Królik',
        'Chomik',
        'Żółw lądowy',
        'Świnka morska',
        'Koń',
        'Osioł',
        'Krowa',
        'Owca',
        'Koza',
        'Świnia',
        'Wół',
        'Kura',
        'Indyk',
        'Gęś',
        'Papuga',
        'Zając',
        'Niedźwiedź polarny',
        'Rysi',
        'Wydra',
        'Manat',
        'Słoń afrykański',
        'Wielbłąd',
        'Antylopa',
        'Puma',
        'Kuna',
        'Sokół',
        'Wrona',
        'Bąk',
        'Czapla',
        'Mewa',
        'Ryś',
        'Jeżozwierz',
        'Pelikany',
        'Wieloryb',
        'Narwal',
        'Foka',
        'Leniwiec',
        'Pangolin',
        'Kozica',
        'Kormoran',
        'Dzik',
        'Bóbr',
        'Lemur',
        'Maki',
        'Koczkodan',
        'Tarantula',
        'Gąsienica',
        'Motyl',
        'Ćma',
        'Mrówka',
        'Pchła',
        'Ślimak',
        'Raki',
      ],
    },
    {
      name: "Przedmiot",
      values: [
        'Laptop',
        'Telefon',
        'Telewizor',
        'Książka',
        'Długopis',
        'Ołówek',
        'Notatnik',
        'Czajnik',
        'Zegarek',
        'Kamera',
        'Słuchawki',
        'Myszka komputerowa',
        'Klawiatura',
        'Drukarka',
        'Lampka biurkowa',
        'Chlebak',
        'Mikrofalówka',
        'Kuchnia',
        'Lodówka',
        'Zmywarka',
        'Ekspres do kawy',
        'Czajnik elektryczny',
        'Toster',
        'Deska do krojenia',
        'Garnek',
        'Patelnia',
        'Szczoteczka do zębów',
        'Szczotka do włosów',
        'Ręcznik',
        'Poduszka',
        'Kołdra',
        'Zasłony',
        'Rama zdjęciowa',
        'Mopa',
        'Odkurzacz',
        'Pralka',
        'Suszarka do włosów',
        'Żelazko',
        'Wieszak',
        'Kubek',
        'Talerz',
        'Sztućce',
        'Butelka',
        'Wazon',
        'Świeczka',
        'Zapałki',
        'Papier toaletowy',
        'Ścierka',
        'Myjka do naczyń',
        'Worek na śmieci',
        'Skrzynka na narzędzia',
        'Narzędzia',
        'Wkrętarka',
        'Wiertarka',
        'Młotek',
        'Śrubokręt',
        'Kleje',
        'Szczypce',
        'Miarka',
        'Termometr',
        'Lustro',
        'Rama obrazu',
        'Kalenderz',
        'Agrafki',
        'Spinacz',
        'Koperta',
        'Zszywacz',
        'Gumki recepturki',
        'Tablica korkowa',
        'Fotel',
        'Stół',
        'Krzesło',
        'Szafa',
        'Komoda',
        'Stolik kawowy',
        'Regal',
        'Lampa stojąca',
        'Podgrzewacz do filiżanek',
        'Zestaw do herbaty',
        'Waga kuchenna',
        'Tarka',
        'Sitko',
        'Mieszadło',
        'Frytkownica',
        'Sokowirówka',
        'Grill',
        'Lodówka',
        'Wagonik',
        'Klepsydra',
        'Skrzynka na listy',
        'Skrzynia',
        'Tablica do rysowania',
        'Płytki CD',
        'Głośnik',
        'Mikrofon',
        'Lampka nocna',
        'Zegarek ścienny',
        'Torba',
        'Plecak',
        'Portfel',
      ],
    },
    {
      name: "Jedzenie",
      values: [
        'Kotlet schabowy',
        'Bigos',
        'Pierogi ruskie',
        'Zupa pomidorowa',
        'Rosół',
        'Gołąbki',
        'Barszcz czerwony',
        'Żurek',
        'Kebab',
        'Pizza Margherita',
        'Spaghetti Bolognese',
        'Lasagne',
        'Tiramisu',
        'Burger z wołowiną',
        'Frytki',
        'Hot dog',
        'Kurczak z rożna',
        'Jajecznica',
        'Omlet',
        'Kiełbasa biała',
        'Sernik',
        'Szarlotka',
        'Lody czekoladowe',
        'Pączki z marmoladą',
        'Kawa espresso',
        'Czekolada z orzechami',
        'Chleb',
        'Bagietka',
        'Rogal',
        'Croissant',
        'Baton Snickers',
        'Baton Mars',
        'Baton Twix',
        'Baton Milky Way',
        'Chipsy Lays',
        'Chipsy Pringles',
        'Orzeszki ziemne',
        'Pistacje',
        'Migdały',
        'Banan',
        'Jabłko',
        'Gruszka',
        'Pomarańcza',
        'Mandarynka',
        'Truskawka',
        'Malina',
        'Borówka amerykańska',
        'Winogrona',
        'Morela',
        'Śliwka',
        'Ananas',
        'Mango',
        'Awokado',
        'Sałatka cezar',
        'Tarta owocowa',
        'Makaron spaghetti',
        'Tortilla',
        'Burrito',
        'Quesadilla',
        'Nachos',
        'Guacamole',
        'Sushi',
        'Tatar wołowy',
        'Sznycel wiedeński',
        'Krewetki',
        'Tuńczyk w sosie własnym',
        'Tosty z szynką',
        'Jajko sadzone',
        'Ryż biały',
        'Sos sojowy',
        'Sos BBQ',
        'Sos czosnkowy',
        'Majonez',
        'Ketchup',
        'Musztarda',
        'Chrzan',
        'Hummus',
        'Baklava',
        'Kawałek tortu czekoladowego',
        'Ciasto marchewkowe',
        'Muffiny czekoladowe',
        'Rogal z dżemem',
        'Kanapka z szynką',
        'Masło orzechowe',
        'Dżem truskawkowy',
        'Nutella',
        'Miód',
        'Chałwa',
        'Beza',
        'Ciasteczka owsiane',
        'Ciasteczka czekoladowe',
        'Galaretka owocowa',
        'Kisiel truskawkowy',
        'Budyń waniliowy',
        'Pieczony ziemniak',
        'Kapusta kiszona',
        'Ogórek kiszony',
        'Marynowane grzyby',
        'Piernik',
      ]
    }
  ]
}