export const CONFIG = {

  USER_ID_KEY: "user_id",
  FORM_KEY: "form",

  URL_ROOT: "/spy",

  MAX_SPIES_LIMIT: 5,

  CATEGORIES: [
    {
      name: "Postać", // 150 postacji, 121 pytań tak/nie, 90 pytań otwartych
      values: [
        'Harry Potter',
        'Darth Vader',
        'Sherlock Holmes',
        'James Bond',
        'Batman',
        'Superman',
        'Myszka Miki',
        'Kubuś Puchatek',
        'Jan Paweł II',
        'Andrzej Duda',
        'Jarosław Kaczyński',
        'Sławomir Mentzen',
        'Robert Lewandowski',
        'Maria Skłodowska-Curie',
        'Spider-Man',
        'Hannibal Lecter',
        'Gandalf',
        'Shrek',
        'Albert Einstein',
        'Adolf Hitler',
        'Barack Obama',
        'Elon Musk',
        'Steve Jobs',
        'Donald Trump',
        'DJ Khaled',
        'Pitbull',
        'Vladimir Putin',
        'Michael Jackson',
        'Elvis Presley',
        'Pele',
        'Usain Bolt',
        'David Beckham',
        'Lionel Messi',
        'Leonardo da Vinci',
        'Isaac Newton',
        'Kleopatra',
        'Napoleon Bonaparte',
        'Mark Zuckerberg',
        'Taylor Swift',
        'Rihanna',
        'Beyonce',
        'Robert Makłowicz',
        'Justin Bieber',
        'Leonardo DiCaprio',
        'Selena Gomez',
        'Drake',
        'Kanye West',
        'Kim Kardashian',
        'Shakira',
        'Ed Sheeran',
        'Lady Gaga',
        'Eminem',
        'Brad Pitt',
        'Angelina Jolie',
        'Katy Perry',
        'Nicki Minaj',
        'Bruno Mars',
        'Cristiano Ronaldo',
        'Kylian Mbappé',
        'Voldemort',
        'Optimus Prime',
        'Simba',
        'Scooby-Doo',
        'Fred Flintstone',
        'Yoda',
        'Jezus',
        'Hulk',
        'Aquaman',
        'Homer Simpson',
        'Sasha Grey',
        'Hermiona Granger',
        'Albus Dumbledore',
        'Anna Lewandowska',
        'Kuba Wojewódzki',
        'Krzysztof Ibisz',
        'Dorota Rabczewska (Doda)',
        'Julia Wieniawa',
        'Magda Gessler',
        'Ewa Chodakowska',
        'Patryk Vega',
        'Wojciech Szczęsny',
        'Mariusz Pudzianowski',
        'Friz',
        'Wersow',
        'Ekipa Friza',
        'PewDiePie (Youtuber)',
        'MrBeast',
        'Logan Paul (Youtuber)',
        'Pinokio',
        'Alicja z Krainy Czarów',
        'Kopciuszek',
        'Jaś i Małgosia',
        'Rudolf Czerwononosy',
        'Tarzan',
        'Jack Sparrow (Piraci z Karaibów)',
        'Neo (Matrix)',
        'Morfeusz (Matrix)',
        'Captain America',
        'Dwayne "The Rock" Johnson',
        'Kamil Stoch',
        'Iga Świątek',
        'Popek',
        'Papież Franciszek',
        'Donald Tusk',
        'Fagata',
        'Young Leosia',
        'Kizo',
        'Adam Małysz',
        'Marcin Gortat',
        'Super Mario',
        'Pikachu',
        'Lara Croft',
        'Geralt z Rivii',
        'Steve z Minecrafta',
        'Władysław Jagiełło',
        'Mieszko I',
        'Czerwony Kapturek',
        'Tinki Winki (Teletubisie)',
        'Królewna Śnieżka',
        'Herkules',
        'Zeus',
        'Kot w butach',
        'Nemo',
        'Joker',
        'Indiana Jones',
        'Forrest Gump',
        'Iron Man',
        'Walter White (Breaking Bad)',
        'Elza (Kraina Lodu)',
        'Buzz Astral',
        'Fiona ze Shreka',
        'Minionek',
        'Sponge Bob',
        'Mikołaj Kopernik',
        'Zorro',
        'Juliusz Cezar',
        'Budda',
        'Mohamed Ali (Bokser)',
        'Borat',
        'Marcin Najman',
        'Zenek Martyniuk',
        'Frodo Baggins',
        'Asterix',
        'Freddie Mercury',
        'Serena Williams',
        'Deadpool',
        'Alladyn',
        'Tabaluga (wieczorynka',
        'Pezet',
        'Dawid Podsiadło',
      ],
      questionsYesNo: [
        'Czy ta postać jest człowiekiem?',
        'Czy ta postać jest fikcyjna?',
        'Czy ta postać pochodzi z filmu, serialu lub gry?',
        'Czy ta postać jest znana globalnie?',
        'Czy ta postać jest żyjącą osobą?',
        'Czy ta postać jest związana z rozrywką (film, muzyka, internet)?',
        'Czy ta postać jest związana ze sportem?',
        'Czy ta postać jest związana z polityką lub historią?',
        'Czy ta postać ma pozytywny wizerunek publiczny?',
        'Czy ta postać jest znana z bycia liderem lub wpływową osobą?',
        'Czy ta postać jest fikcyjną postacią z uniwersum dla dzieci?',
        'Czy ta postać jest postacią z kreskówki lub animacji?',
        'Czy ta postać ma supermoce lub nadzwyczajne umiejętności?',
        'Czy ta postać jest powiązana z internetem lub mediami społecznościowymi?',
        'Czy ta postać jest znana głównie w Polsce?',
        'Czy ta postać jest szeroko rozpoznawalna w kulturze popularnej?',
        'Czy ta postać kojarzy się głównie z jedną konkretną rolą lub cechą?',
        'Czy ta postać jest częściej kojarzona z fikcją niż rzeczywistością?',
        'Czy ta postać ma silnie utrwalony wizerunek w mediach?',
        'Czy ta postać jest bardziej pozytywnie niż negatywnie odbierana?',
        'Czy ta postać jest znana z długotrwałej obecności w swojej dziedzinie?',
        'Czy ta postać jest łatwa do rozpoznania po jednym opisie lub haśle?',
        'Czy ta postać jest kojarzona z dużą popularnością międzynarodową?',
        'Czy ta postać ma charakterystyczny styl, cechę lub motyw przewodni?',
        'Czy ta postać jest częścią większej serii, uniwersum lub grupy?',
        'Czy ta postać jest kojarzona z silną emocją (strach, podziw, humor)?',
        'Czy ta postać jest bardziej współczesna niż historyczna?',
        'Czy ta postać jest często używana jako symbol lub ikona?',
        'Czy ta postać jest łatwa do odróżnienia od innych podobnych postaci?',
        'Czy ta postać jest znana z jednej dominującej cechy lub osiągnięcia?',
        'Czy ta postać jest kojarzona głównie z rozrywką?',
        'Czy ta postać jest kojarzona z osiągnięciami, a nie fikcyjną historią?',
        'Czy ta postać jest częścią globalnie znanego uniwersum?',
        'Czy ta postać ma rozpoznawalny wygląd lub symbol?',
        'Czy ta postać jest często pojawiająca się w memach lub popkulturze internetowej?',
        'Czy ta postać jest kojarzona z byciem liderem lub autorytetem?',
        'Czy ta postać jest związana z dużą grupą fanów lub społecznością?',
        'Czy ta postać jest znana z jednej głównej dziedziny aktywności?',
        'Czy ta postać jest kojarzona z historią lub wydarzeniami publicznymi?',
        'Czy ta postać jest często przedstawiana w filmach, książkach lub serialach?',
        'Czy ta postać jest bardziej ikoniczna niż realistyczna?',
        'Czy ta postać jest łatwa do narysowania lub symbolicznego przedstawienia?',
        'Czy ta postać jest kojarzona z konkretną epoką lub okresem?',
        'Czy ta postać jest częścią duetu, grupy lub zespołu?',
        'Czy ta postać jest rozpoznawalna nawet bez znajomości szczegółów?',
        'Czy ta postać jest raczej pozytywnie niż negatywnie odbierana przez większość ludzi?',
        'Czy ta postać jest bardziej „ikoniczna” niż „realistyczna” w swoim wizerunku?',
        'Czy ta postać kojarzy się bardziej z jedną silną cechą niż z wieloma różnymi?',
        'Czy ta postać wywołuje u ludzi natychmiastowe skojarzenie bez zastanowienia?',
        'Czy ta postać jest bardziej „większa niż życie” niż zwyczajna?',
        'Czy ta postać jest częściej wspominana w żartach, memach lub popkulturze niż w poważnych kontekstach?',
        'Czy ta postać ma wizerunek, który trudno pomylić z kimkolwiek innym?',
        'Czy ta postać jest bardziej rozpoznawalna wizualnie niż z opisu?',
        'Czy ta postać jest kojarzona z czymś, co można streścić jednym zdaniem?',
        'Czy ta postać jest raczej symbolem niż „zwykłą osobą lub rolą”?',
        'Czy ta postać jest częściej przedstawiana w uproszczonej formie niż realistycznej?',
        'Czy ta postać jest częścią historii, którą większość ludzi zna „ogólnie”, a nie szczegółowo?',
        'Czy ta postać ma silny „mit” lub legendę wokół siebie?',
        'Czy ta postać jest bardziej znana z tego, co reprezentuje, niż z tego, co dokładnie robi?',
        'Czy ta postać byłaby łatwa do rozpoznania nawet w bardzo zniekształconym opisie?',
        'Czy ta postać jest raczej „jednowymiarowa w skojarzeniach”, niż złożona?',
        'Czy ta postać jest bardziej emocjonalnie niż logicznie kojarzona przez ludzi?',
        'Czy ta postać jest często używana jako przykład czegoś w kulturze lub rozmowach?',
        'Czy ta postać ma bardzo silny „pierwszy efekt skojarzenia” u większości ludzi?',
        'Czy ta postać jest bardziej „rozpoznawalnym znakiem” niż osobą lub postacią w pełnym sensie?',
        'Czy ta postać jest mężczyzną?',
        'Czy ta postać jest kobietą?',
        'Czy ta postać jest związana z nauką lub technologią?',
        'Czy ta postać jest związana z biznesem lub finansami?',
        'Czy ta postać pochodzi z Europy?',
        'Czy ta postać pochodzi z Ameryki Północnej?',
        'Czy ta postać pochodzi z Azji?',
        'Czy ta postać pochodzi z czasów współczesnych (po 2000 roku)?',
        'Czy ta postać pochodzi sprzed XX wieku?',
        'Czy ta postać jest bohaterem?',
        'Czy ta postać jest człowiekiem o historycznym znaczeniu?',
        'Czy ta postać jest kojarzona z edukacją lub szkołą?',
        'Czy ta postać jest kojarzona z wojskiem lub służbami?',
        'Czy ta postać jest związana z religią lub duchowością?',
        'Czy ta postać jest związana z literaturą (książki, powieści)?',
        'Czy ta postać jest znana głównie z internetu (np. influencer, streamer)?',
        'Czy ta postać jest związana z telewizją?',
        'Czy ta postać jest związana z muzyką jako artysta?',
        'Czy ta postać jest związana z tworzeniem treści (np. reżyser, autor, twórca)?',
        'Czy ta postać jest młoda (poniżej 30 lat w swoim uniwersum/rzeczywistości)?',
        'Czy ta postać jest starszą osobą (powyżej 50 lat)?',
        'Czy ta postać ma charakterystyczny strój lub uniform?',
        'Czy ta postać używa broni lub specjalnych narzędzi?',
        'Czy ta postać posiada nadludzką siłę fizyczną?',
        'Czy ta postać jest inteligentna?',
        'Czy ta postać jest związana z komedią lub humorem?',
        'Czy ta postać jest związana z dramatem lub poważną tematyką?',
        'Czy ta postać jest samotnikiem?',
        'Czy ta postać jest przywódcą grupy?',
        'Czy ta postać ma zwierzęcego towarzysza lub powiązanie ze zwierzętami?',
        'Czy ta postać jest związana z magią lub fantasy?',
        'Czy ta postać pochodzi z science fiction?',
        'Czy ta postać jest często przedstawiana jako geniusz?',
        'Czy ta postać jest znana z odwagi?',
        'Czy ta postać jest znana z humoru?',
        'Czy ta postać ma tragiczną historię?',
        'Czy ta postać jest związana z podróżami lub eksploracją?',
        'Czy ta postać jest znana z rywalizacji z inną postacią?',
        'Czy ta postać jest częścią drużyny lub zespołu?',
        'Czy ta postać ma nieludzki wygląd (np. potwór, robot, istota fantastyczna)?',
        'Czy ta postać jest znana z jednej konkretnej sceny lub momentu?',
        'Czy ta postać jest często cytowana lub przytaczana?',
        'Czy ta postać jest bardziej znana wśród młodzieży czy dorosłych?',
        'Czy ta postać jest związana z grami komputerowymi lub e-sportem?',
        'Czy ta postać jest związana z mediami tradycyjnymi (gazety, radio)?',
        'Czy ta postać jest łatwa do opisania jednym słowem?',
        'Czy ta postać występuje w animacji',
        'Czy ta postać jest związana z biznesem?',
        'Czy ta postać jest znana bardziej z wpływu niż z bezpośrednich działań?',
        'Czy ta postać jest często interpretowana inaczej przez różnych odbiorców?',
        'Czy ta postać jest znana głównie z jednego wydarzenia w historii?',
        'Czy ta postać jest bardziej legendą niż konkretną osobą?',
        'Czy ta postać ma ważne relacje z inną znaną postacią?',
        'Czy ta postać jest częścią rozbudowanego uniwersum?',
        'Czy ta postać jest rozpoznawalna głównie przez kontekst, a nie imię?',
        'Czy ta postać jest trudna do jednoznacznego sklasyfikowania w jednej kategorii?'
      ],
      questionsOpen: [
        'Wymień 2 cechy tej postaci.',
        'Wymień jedną cechę tej postaci.',
        'Wymień 2 słowa z którymi kojarzy się ta postać',
        'Wymień jedno słowo z jakim kojarzy Ci się ta postać',
        'Gdyby ta postać byłaby meblem, to jakim?',
        'Jaki film mogłaby lubić ta postać?',
        'Z czym najbardziej kojarzy się ta postać?',
        'Gdzie moglibyśmy spotkać tę postać?',
        'Jak ta postać mogłaby pachnieć?',
        'Jakim jednym słowem opisałbyś tę postać?',
        'Jakimi dwoma słowami opisałbyś tę postać?',
        'Jaką emocję najczęściej wywołuje ta postać?',
        'Jak wyglądałby dzień tej postaci?',
        'Co ta postać robi na co dzień?',
        'Jakie ubranie najbardziej pasuje do tej postaci?',
        'Jaką muzykę mogłaby lubić ta postać?',
        'Jaki kolor najlepiej pasuje do tej postaci?',
        'Jakie zwierzę najbardziej kojarzy się z tą postacią?',
        'Jak ta postać mówi (styl wypowiedzi)?',
        'Jakiego drinka zamówiłaby ta postać?',
        'Jakie miejsce idealnie pasuje do tej postaci?',
        'Zrób jakiś gest który pasuje do tej postaci?',
        'Pokaż jak ta postać zatańczyłaby na imprezie?',
        'Jakiej rzeczy ta postać zawsze by potrzebowała?',
        'Co ta postać najprawdopodobniej trzyma w ręku?',
        'Jak ta postać spędza wolny czas?',
        'Z kim ta postać mogłaby się przyjaźnić?',
        'Kogo ta postać mogłaby nie lubić?',
        'Jakie jedzenie pasuje do tej postaci?',
        'Co ta postać robi, gdy jest sama?',
        'Co jest najbardziej charakterystyczne w tej postaci?',
        'Jak inni ludzie postrzegają tę postać?',
        'Czy ta postać jest bardziej samotnikiem czy liderem?',
        'Jak ta postać mogłaby się śmiać?',
        'Jak ta postać mogłaby się złościć?',
        'Co ta postać uważa za najważniejsze w życiu?',
        'Jak ta postać mogłaby się ubierać na co dzień?',
        'Co byłoby jej „znakiem rozpoznawczym”?',
        'Co ta postać dałaby w prezencie komuś na urodziny?',
        'Jak ta postać zachowałaby się, gdyby weszła do dużego sklepu?',
        'Jakie auto pasowałoby do tej postaci?',
        'Co ta postać zrobiłaby, gdyby wygrała milion złotych?',
        'Jak ta postać zachowałaby się na weselu?',
        'Jak ta postać zachowałaby się zatrzaśnięta w windzie?',
        'Jak ta postać zachowałaby się w restauracji?',
        'Jaką tajną umiejętność mogłaby mieć ta postać?',
        'Wymień 2 rzeczy jaką ta postać mogłaby lubić robić?',
        'Wymień 2 rzeczy jaką ta postać mogłaby lubić jeść?',
        'Jakie miejsce na świecie najbardziej pasuje do tej postaci?',
        'Co ta postać robi, gdy coś jej nie wychodzi?',
        'Opisz idealny poranek tej postacji',
        'Jakie ma podejście do pieniędzy?',
        'Co ta postać uważa za największą stratę czasu?',
        'Jak ta postać reaguje na nowe znajomości?',
        'Jak ta postać zachowuje się w sytuacji konfliktu?',
        'Jak ta postać spędziłaby urlop w tropikach?',
        'Wymień 2 rzeczy które ta postać zabrałaby na bezludną wyspę',
        'Co ta postać myśli o zasadach i ich przestrzeganiu?',
        'Co ta postać robi, gdy ma dużo wolnego czasu?',
        'Co ta postać uważa za luksus?',
        'Wymień 2 rzeczy jakie ta postać mogłaby robić w nocy',
        'Wymień 2 sporty jakie ta postać mogłaby lubić',
        'Jak ta postać zachowuje się na imprezie?',
        'Co ta postać mogłaby zbierać lub kolekcjonować?',
        'Jak ta postać okazuje wdzięczność?',
        'Co ta postać robi w weekendy?',
        'Jak często ta postać spędza czas z przyjaciółmi',
        'Wymień 2 cechy które ta postać może lubić u innych',
        'Jak ta postać zachowuje się wobec zwierząt?',
        'Co motywuje tę postać?',
        'Co ta postać mogłaby zrobić, żeby się zrelaksować?',
        'Co ta postać robi, gdy ma trudną decyzję?',
        'Jak ta postać zachowuje się wobec dzieci?',
        'Co ta postać robi, gdy ma sekret?',
        'Jakim środkiem transportu mogłaby jeździć ta postać',
        'Jakie oceny to postać mogłaby mieć w szkole?',
        'Jak ta postać zachowałaby się w bibliotece?',
        'Jakie danie jako pierwsze zjadłaby ta postać na wigilii?',
        'Do jakiego kraju pojechałaby ta postać na wakacje?',
        'Jakiej rzeczy ta postać najbardziej się boi?',
        'Jakich aplikacji najczęściej używałaby ta postać?',
        'Jaką jedną słabość ma ta postać?',
        'Jaką jedną supermoc mogłaby mieć ta postać?',
        'Czy ta postać często się spóźnia czy zawsze jest punktualna?',
        'Jaka pora roku najlepiej oddaje jej charakter?',
        'Co najbardziej irytuje tę postać u innych?',
        'Pokaż jak ta postać mogłaby chodzić',
        'Pokaż jak ta postać mogłaby zareagować na szokujące wiadomości',
        'Pokaż jak ta postać mogłaby witać się z kimś znajomym',
        'Pokaż jak ta postać mogłaby odmawić czegoś bez słów'
      ]
    },
    {
      name: "Kraj", // 52 kraje, 89 pytań tak/nie, 58 pytań otwartych
      values: [
        'Stany Zjednoczone',
        'Kanada',
        'Wielka Brytania',
        'Niemcy',
        'Francja',
        'Włochy',
        'Hiszpania',
        'Ukraina',
        'Szwecja',
        'Czechy',
        'Kolumbia',
        'Chile',
        'Maroko',
        'Portugalia',
        'Papua-Nowa Gwinea',
        'Australia',
        'Japonia',
        'Nigeria',
        'Chiny',
        'Indie',
        'Korea Północna',
        'Korea Południowa',
        'Izreal',
        'Iran',
        'Argentyna',
        'Brazylia',
        'Rosja',
        'Meksyk',
        'Szwajcaria',
        'Norwegia',
        'Polska',
        'Tajlandia',
        'Fiji',
        'Chorwacja',
        'Egipt',
        'Holandia',
        'Austria',
        'Finlandia',
        'Irlandia',
        'Grecja',
        'Turcja',
        'Zjednoczone Emiraty Arabskie',
        'Irak',
        'Pakistan',
        'Bangladesz',
        'Wietnam',
        'Filipiny',
        'Nowa Zelandia',
        'RPA (Republika Południowej Afryki)',
        'Kenia',
        'Malediwy',
        'Dżibuti'
      ],
      questionsYesNo: [
        'Czy jedzenie tam jest ostre?',
        'Czy to popularny kierunek wakacyjny?',
        'Czy ten kraj jest znany z muzyki lub tańca?',
        'Czy w tym kraju jest gorąco przez większość roku?',
        'Czy tamtejsza kuchnia jest znana na całym świecie?',
        'Czy obowiązuje tam ruch lewostronny?',
        'Czy można tam pojechać samochodem z Polski?',
        'Czy to kraj europejski?',
        'Czy chciałbyś teraz znaleźć się w tym kraju?',
        'Czy w tym kraju żyją dzikie zwierzęta, które można spotkać tylko tam?',
        'Czy ten kraj ma piękne kadry filmowe?',
        'Czy w tym kraju jest dużo gór?',
        'Czy w tym kraju jest dużo lasów?',
        'Czy waluta tego kraju jest inna niż euro?',
        'Czy w tym kraju często świeci słońce?',
        'Czy mieszkańcy tego kraju są znani z punktualności?',
        'Czy to kraj o dużej powierzchni?',
        'Czy w tym kraju pije się dużo kawy?',
        'Czy to kraj, do którego trudno się dostać?',
        'Czy ludzie tam lubią piłkę nożną?',
        'Czy kraj ten ma monarchię?',
        'Czy to kraj, w którym można zobaczyć pustynię?',
        'Czy w tym kraju używa się alfabetu innego niż łaciński?',
        'Czy ten kraj ma sąsiada, z którym ma napięte relacje?',
        'Czy ludzie tam często jedzą ryż?',
        'Czy to kraj, który organizował igrzyska olimpijskie?',
        'Czy w tym kraju produkuje się znane marki ubrań lub samochodów?',
        'Czy ludzie tam są znani z gościnności?',
        'Czy to kraj, w którym mógłbyś zamieszkać?',
        'Czy ten kraj ma dostęp do morza?',
        'Czy w tym kraju jeździ się dużo na rowerach?',
        'Czy ten kraj słynie z zabytków wpisanych na listę UNESCO?',
        'Czy język tego kraju jest trudny do nauki?',
        'Czy gospodarka tego kraju jest bardzo rozwinięta?',
        'Czy ten kraj jest znany z wina lub alkoholu?',
        'Czy w tym kraju dużo się poluje lub łowi ryby?',
        'Czy kraj ten jest częścią Unii Europejskiej?',
        'Czy miejscowa religia jest bardzo ważna dla mieszkańców?',
        'Czy w tym kraju znajdziemy wulkany?',
        'Czy ten kraj słynie z nowoczesnych technologii?',
        'Czy kraj ten znany jest ze swoich festiwali lub karnawałów?',
        'Czy ten kraj jest mniejszy od Polski?',
        'Czy ten kraj jest większy od Polski?',
        'Czy można tam zobaczyć wieżowce?',
        'Czy w tym kraju były kiedyś królewskie kolonie?',
        'Czy w tym kraju mówi się w więcej niż jednym języku urzędowym?',
        'Czy ten kraj ma jedną z najsilniejszych armii na świecie?',
        'Czy w tym kraju są dżungle lub tropikalne lasy?',
        'Czy ten kraj jest znany z nauki lub wynalazków?',
        'Czy kraj ten ma bardzo stare tradycje?',
        'Czy ludzie z tego kraju są znani z poczucia humoru?',
        'Czy to kraj, do którego Polacy często wyjeżdżają do pracy?',
        'Czy ten kraj słynie z dobrej infrastruktury i transportu?',
        'Czy w tym kraju panuje głównie zimny klimat?',
        'Czy kraj ten ma dostęp do oceanu?',
        'Czy w tym kraju płaci się dużo podatków?',
        'Czy ten kraj jest bardzo górzysty?',
        'Czy w tym kraju popularna jest kuchnia oparta na makaronie lub pieczywie?',
        'Czy narodowy sport tego kraju jest bardzo charakterystyczny i rozpoznawalny?',
        'Czy ten kraj jest znany z wysokich cen życia?',
        'Czy w tym kraju jest dużo wysp?',
        'Czy ten kraj ma dostęp do dwóch oceanów lub dwóch mórz?',
        'Czy w tym kraju występują trzęsienia ziemi?',
        'Czy w tym kraju występują huragany lub tajfuny?',
        'Czy ten kraj jest znany z produkcji ropy naftowej?',
        'Czy w tym kraju znajdują się słynne zabytki światowe?',
        'Czy w tym kraju jedzenie często jest bardzo tłuste lub ciężkie?',
        'Czy w tym kraju popularne są sporty zimowe?',
        'Czy w tym kraju są bardzo surowe prawa?',
        'Czy w tym kraju panuje demokracja?',
        'Czy w tym kraju żyją bardzo egzotyczne zwierzęta?',
        'Czy w tym kraju popularne są targi uliczne?',
        'Czy w tym kraju są popularne street foody?',
        'Czy w tym kraju powszechne są rowery jako transport miejski?',
        'Czy w tym kraju znajduje się znana stolica światowej mody?',
        'Czy w tym kraju produkuje się znane samochody?',
        'Czy w tym kraju produkuje się znane smartfony lub elektronikę?',
        'Czy w tym kraju występują bardzo wysokie temperatury latem?',
        'Czy w tym kraju zimy są bardzo mroźne?',
        'Czy ten kraj jest bardzo kontrastowy pod kątem zarobków?',
        'Czy w tym kraju jest duża imigracja?',
        'Czy z tego kraju pochodzi wiele znanych sportowców?',
        'Czy ten kraj jest znany z niskiej przestępczości?',
        'Czy w tym kraju istnieją bardzo duże metropolie?',
        'Czy w tym kraju ludzie często mówią więcej niż jednym językiem?',
        'Czy w tym kraju występuje klimat tropikalny?',
        'Czy w tym kraju występuje klimat śródziemnomorski?',
        'Czy w tym kraju jest dużo parków narodowych?',
        'Czy ten kraj ma charakterystyczne stroje ludowe?'
      ],
      questionsOpen: [
        'Jaka rzecz najbardziej kojarzy się z tym krajem?',
        'Jakie 2 rzeczy najbardziej kojarzą się z tym krajem?',
        'Jak wyglądałby idealny dzień w tym kraju?',
        'Jakie jedzenie najbardziej kojarzy się z tym krajem?',
        'Jaką pogodę najczęściej wyobrażasz sobie w tym kraju?',
        'Jak brzmi typowy „klimat” tego kraju?',
        'Powiedz dowolną rzecz o tym kraju',
        'Jakie zwierzę najlepiej symbolizuje ten kraj?',
        'Jaką muzykę mógłbyś skojarzyć z tym krajem?',
        'Jak wyglądałaby flaga tego kraju w twojej interpretacji (opisz)?',
        'Jakie stereotypowe zachowanie ludzi z tego kraju przychodzi ci do głowy?',
        'Jak wyglądałby krajobraz tego kraju?',
        'Jakie ubrania kojarzą się z tym krajem?',
        'Jakie 2 słowa najlepiej opisują ten kraj?',
        'Jakie jedno słowo najlepiej opisuje ten kraj?',
        'Jaki kolor kojarzy ci się z tym krajem?',
        'Co turysta powinien tam koniecznie zobaczyć?',
        'Jakie emocje budzi ten kraj?',
        'Jakie kolory dominują w twoim wyobrażeniu tego kraju?',
        'Jakie filmy lub klimat filmowy pasuje do tego kraju?',
        'Jakie sporty są z nim najbardziej kojarzone?',
        'Jaką porę roku najbardziej kojarzysz z tym krajem?',
        'Jakie języki lub dźwięki kojarzą się z tym krajem?',
        'Jakie budynki lub architektura pasują do tego kraju?',
        'Jak wyglądałby przewodnik po tym kraju?',
        'Jakie legendy lub historie mogą się z nim kojarzyć?',
        'Jakie zwierzęta mogłyby być symbolem tego kraju?',
        'Pokaż jak wyglądałby taniec kojarzony z tym krajem?',
        'Pokaż jak mógłby siedzieć typowy obywatel tego kraju',
        'Jaką historię mógłby opowiedzieć ktoś z tego kraju?',
        'Jak wyglądałby sklep w tym kraju?',
        'Jakie są najbardziej znane symbole tego kraju?',
        'Jakie wakacje kojarzą się z tym krajem?',
        'Jak wyglądałby styl życia mieszkańców tego kraju?',
        'Jak wyglądałby krajobraz widziany z samolotu nad tym krajem?',
        'Jakie dźwięki kojarzą się z tym krajem?',
        'Jak wyglądałby film reklamujący ten kraj?',
        'Jaka rzecz mogłaby pochodzić z tego kraju (nie musi to byc prawda)?',
        'Jak wygląda system transportu w tym kraju?',
        'Jak wygląda typowy dom w tym kraju?',
        'Jakie są typowe zawody w tym kraju?',
        'Jak wygląda szkolnictwo w tym kraju?',
        'Opisz jak ważna jest rodzina w tym kraju?',
        'Jak wygląda codzienna rutyna mieszkańców rano?',
        'Jak wygląda codzienna rutyna mieszkańców wieczorem?',
        'Jaki fast food mógłby kojarzyć się z tym krajem?',
        'Zanuć lub opisz jak mogłaby brzmieć muzyka z tego kraju',
        'Jakie są relacje tego kraju z sąsiadami?',
        'Jak wygląda nocne życie w tym kraju?',
        'Jakie elementy przyrody są najbardziej charakterystyczne?',
        'Jak wygląda system edukacji wyższej, czy dużo jest osób wykształconych?',
        'Jaka książka lub film mogłaby kojarzyć się z tym krajem?',
        'Jaki jest jeden z problemów tego kraju?',
        'Jak wyglądałaby reklama tego kraju w telewizji?',
        'Jakie 2 produkty spożywcze mogą kojarzyć się z tym krajem?',
        'Jaka jest statystyczna wielkość rodziny w tym kraju?',
        'Jaka jest przykładowa forma rozrywki w tym kraju?',
        'Podaj przykład popularnego środku transportu codziennego',
        'Jakie są ulubione napoje mieszkańców tego kraju?'
      ]
    },
    {
      name: "Miejsce", // 121 miejsc, 142 pytań tak/nie, 90 pytań otwartych
      values: [
        'IKEA',
        'Zara',
        'Apple Store',
        'Wieża Eiffla',
        'Koloseum',
        'Wielki Mur Chiński',
        'Times Square',
        'Big Ben',
        'Aquapark',
        'Fajka Bar Żurawia',
        'Muzeum',
        'Zoo',
        'Stadion',
        'Biedronka',
        'Rossmann',
        'Castorama',
        'Siłownia',
        'Mount Everest',
        'Piramida Cheopsa',
        'Budka z kebabem',
        'Biuro',
        'Pizzeria',
        'Akademik',
        'Lotnisko',
        'Dworzec kolejowy',
        'Stacja metra',
        'Przystanek autobusowy',
        'Biblioteka',
        'Szpital',
        'Apteka',
        'Komisariat policji',
        'Straż pożarna',
        'Sąd',
        'Urząd pocztowy',
        'Urząd skarbowy',
        'Bank',
        'Kino',
        'Teatr',
        'Opera',
        'Filharmonia',
        'Galeria handlowa',
        'Sklep zoologiczny',
        'Księgarnia',
        'Cukiernia',
        'Piekarnia',
        'Lodziarnia',
        'Kawiarnia',
        'Sushi bar',
        'Hotel',
        'Pensjonat',
        'Schronisko górskie',
        'Kemping',
        'Plaża',
        'Latarnia morska',
        'Port',
        'Most',
        'Tunel',
        'Autostrada',
        'Parking',
        'Myjnia samochodowa',
        'Warsztat samochodowy',
        'Stacja benzynowa',
        'Wulkan',
        'Park narodowy',
        'Ogród botaniczny',
        'Park rozrywki',
        'Cyrk',
        'Kręgielnia',
        'Escape room',
        'Kasyno',
        'Lodowisko',
        'Basen',
        'Boisko',
        'Kort tenisowy',
        'Pole golfowe',
        'Skatepark',
        'Studio nagraniowe',
        'Uniwersytet',
        'Laboratorium',
        'Cmentarz',
        'Kościół',
        'Świątynia buddyjska',
        'Pałac',
        'Młyn',
        'Winiarnia',
        'Browar',
        'Hala targowa',
        'Sklep z elektroniką',
        'Salon fryzjerski',
        'Salon tatuażu',
        'Gabinet dentystyczny',
        'Statua Wolności',
        'Luwr',
        'Disneyland',
        'Pałac Kultury i Nauki',
        'Zamek Królewski na Wawelu',
        'Łazienki Królewskie',
        'Morskie Oko',
        'Krupówki',
        'Kopalnia Soli w Wieliczce',
        'Molo w Sopocie',
        'Centrum Nauki Kopernik',
        'Muzeum Powstania Warszawskiego',
        'Sahara',
        'Burdż Chalifa',
        'Dom weselny',
        'Sklep rowerowy',
        'Sklep muzyczny',
        'Targ rybny',
        'Pralnia',
        'Gabinet weterynaryjny',
        'Tor kartingowy',
        'Wyciąg narciarski',
        'Synagoga',
        'Jaskinia',
        'Tutaj (miejsce gdzie jesteście)',
        'Tutaj (miejsce gdzie jesteście)',
        'Tutaj (miejsce gdzie jesteście)',
        'Winda',
        'Piwnica',
        'Więzienie'
      ],
      questionsYesNo: [
        'Czy zorganizowałbyś tam urodziny?',
        'Czy dzieci mogą się tam czegoś nauczyć?',
        'Czy poszedłbyś tam na randkę?',
        'Czy zorganizowałbyś tam komunię dziecka?',
        'Czy to miejsce jest ciasne?',
        'Czy jest tam się gdzie schować?',
        'Czy byłeś tam w ostatnich 3 dniach?',
        'Jak często tam chodzisz?',
        'Czy to miejsce jest blisko nas?',
        'Czy chciałbyś tam spędzić cały dzień?',
        'Czy to miejsce jest raczej głośne?',
        'Czy można tam coś kupić?',
        'Czy trzeba tam zachowywać ciszę?',
        'Czy to miejsce kojarzy się z pracą?',
        'Czy jest tam dużo ludzi?',
        'Czy można tam coś zjeść?',
        'Czy można tam robić zdjęcia?',
        'Czy trzeba płacić za wejście?',
        'Czy to miejsce jest na zewnątrz?',
        'Czy trzeba mieć specjalne ubranie, żeby tam wejść?',
        'Czy bywa tam gorąco?',
        'Czy w tym miejscu można się dobrze bawić?',
        'Czy to miejsce jest bezpieczne?',
        'Czy można tam znaleźć dzieci?',
        'Czy można tam znaleźć zwierzęta?',
        'Czy to miejsce jest popularne wśród turystów?',
        'Czy da się tam usiąść?',
        'Czy słychać tam muzykę?',
        'Czy ktoś tam pracuje w mundurze?',
        'Czy to miejsce znajduje się w budynku?',
        'Czy można tam coś zbudować?',
        'Czy to miejsce jest czyste?',
        'Czy bywa tam stresująco?',
        'Czy można tam odpocząć?',
        'Czy to miejsce ma zapach, który łatwo zapamiętać?',
        'Czy są tam jakieś zasady, których trzeba przestrzegać?',
        'Czy można tam spędzić romantyczny wieczór?',
        'Czy można tam krzyczeć?',
        'Czy to miejsce ma określone godziny otwarcia?',
        'Czy w tym miejscu pracuje więcej niż 10 osób?',
        'Czy są tam miejsca siedzące?',
        'Czy ludzie tam przychodzą z własnej woli?',
        'Czy można się tam zgubić?',
        'Czy jest tam toaleta?',
        'Czy to miejsce jest w centrum miasta?',
        'Czy w tym miejscu są schody?',
        'Czy można tam płacić kartą?',
        'Czy można tam pić alkohol?',
        'Czy są tam jakieś pojazdy?',
        'Czy trzeba tam mieć bilet?',
        'Czy to miejsce ma logo?',
        'Czy ktoś tam nosi kask?',
        'Czy jest tam klimatyzacja?',
        'Czy to miejsce ma sufit?',
        'Czy można tam rozmawiać przez telefon?',
        'Czy można tam tańczyć?',
        'Czy to miejsce ma dobre oświetlenie?',
        'Czy jest tam głośno przez cały czas?',
        'Czy można tam kogoś spotkać przypadkiem?',
        'Czy ktoś tam daje wskazówki lub prowadzi innych?',
        'Czy w tym miejscu widać niebo?',
        'Czy można tam się ubrudzić?',
        'Czy to miejsce kojarzy się z ruchem?',
        'Czy można tam coś zobaczyć przez szybę?',
        'Czy jest tam coś do jedzenia lub picia na sprzedaż?',
        'Czy ktoś tam sprząta regularnie?',
        'Czy to miejsce kojarzy się z odpoczynkiem?',
        'Czy w tym miejscu widać wodę?',
        'Czy można tam słuchać muzyki na żywo?',
        'Czy trzeba tam zachowywać powagę?',
        'Czy są tam uniformy?',
        'Czy można tam zrobić coś sportowego?',
        'Czy w tym miejscu są ekrany?',
        'Czy można tam siedzieć przez dłuższy czas?',
        'Czy są tam rzędy lub kolejki?',
        'Czy to miejsce ma wyraźny zapach jedzenia?',
        'Czy można tam coś kupić za gotówkę?',
        'Czy ktoś tam daje rozkazy?',
        'Czy to miejsce ma coś wspólnego z nauką?',
        'Czy w tym miejscu jest ciepło przez cały rok?',
        'Czy można tam spać?',
        'Czy to miejsce bywa hałaśliwe tylko czasami?',
        'Czy ktoś tam nosi garnitur?',
        'Czy można tam coś wypożyczyć?',
        'Czy w tym miejscu się klaszcze?',
        'Czy ludzie tam czekają na coś?',
        'Czy są tam fotele lub kanapy?',
        'Czy można tam zobaczyć plakaty lub napisy?',
        'Czy ktoś tam przemawia do ludzi?',
        'Czy to miejsce kojarzy się z jedzeniem?',
        'Czy są tam okna?',
        'Czy trzeba tam coś podpisać?',
        'Czy w tym miejscu łatwo się zgubić?',
        'Czy ktoś tam śpiewa?',
        'Czy można tam zobaczyć coś dużego?',
        'Czy ktoś tam jest w pośpiechu?',
        'Czy można tam usłyszeć śmiech?',
        'Czy to miejsce ma jakiś zapach charakterystyczny?',
        'Czy można tam coś kupić do jedzenia?',
        'Czy ktoś tam siedzi za ladą lub biurkiem?',
        'Czy w tym miejscu widać rośliny?',
        'Czy trzeba tam coś rezerwować wcześniej?',
        'Czy to miejsce działa w nocy?',
        'Czy są tam dźwięki maszyn?',
        'Czy ktoś tam nosi identyfikator?',
        'Czy można tam znaleźć lustra?',
        'Czy ktoś tam sprzedaje coś?',
        'Czy to miejsce kojarzy się z podróżą?',
        'Czy można tam znaleźć zegar?',
        'Czy mówi się tam w języku, który rozpoznajesz?',
        'Czy to miejsce ma dostęp do morza?',
        'Czy jedzenie tam jest ostre?',
        'Czy ludzie tam często się uśmiechają?',
        'Czy w tym miejscu można głośno śpiewać?',
        'Czy to miejsce jest bardzo duże?',
        'Czy można tam robić zakupy?',
        'Czy w tym miejscu trzeba czekać w kolejce?',
        'Czy można tam spotkać obcych ludzi?',
        'Czy ktoś tam pracuje za biurkiem?',
        'Czy w tym miejscu jest dużo światła?',
        'Czy to miejsce kojarzy się z pieniędzmi?',
        'Czy łatwo tam trafić?',
        'Czy to miejsce jest popularne w weekendy?',
        'Czy można tam spędzić kilka godzin?',
        'Czy w tym miejscu można coś obejrzeć?',
        'Czy ktoś tam daje instrukcje?',
        'Czy to miejsce może być niebezpieczne?',
        'Czy dociera tam transport publiczny?',
        'Czy można tam wejść za darmo?',
        'Czy to miejsce jest związane z kulturą?',
        'Czy są tam dekoracje zmieniające się wraz z porami roku?',
        'Czy w tym miejscu są długie korytarze?',
        'Czy to miejsce znajduje się głównie w mieście?',
        'Czy można tam coś wysłać?',
        'Czy w tym miejscu ludzie się ubierają elegancko?',
        'Czy ktoś tam sprzedaje bilety?',
        'Czy to miejsce ma wyznaczone strefy lub sektory?',
        'Czy w tym miejscu można coś wypożyczyć?',
        'Czy to miejsce jest dobrze chronione?',
        'Czy to miejsce wygląda inaczej nocą niż za dnia?',
        'Czy w tym miejscu są mapy lub tablice informacyjne?',
        'Czy można tam usiąść na trawie?',
        'Czy jest tam dużo przestrzeni do chodzenia?'
      ],
      questionsOpen: [
        'Z jakim dniem tygodnia może kojarzyć się to miejsce (czy to bez znaczenia)?',
        'Zrób dźwięk jaki można tu usłyszeć',
        'Pokaż jak wszedłbyś do tego miejsca',
        'Ile czasu wytrzymałbyś w tym miejscu?',
        'Czy chciałbyś się tam teraz znaleźć?',
        'Czy mógłbyś tam zamieszkać na 1 miesiąc?',
        'Opisz jak pachnie w tym miejscu',
        'Podaj jedno słowo które może kojarzyć się z tym miejscem',
        'Podaj dwa słowa które mogą kojarzyć się z tym miejscem',
        'Jak wyglądałby idealny dzień w tym miejscu?',
        'Do czego to miejsce najbardziej by się nadawało?',
        'Jakie 2 rzeczy kojarzą się z tym miejscem?',
        'Jaka jedna rzecz kojarzy się z tym miejscem?',
        'Jaką rzecz można tam znaleźć?',
        'Jaką atmosferę ma to miejsce (w 1 zdaniu)?',
        'Jakie emocje wywołuje to miejsce?',
        'Jakie dźwięki można tam usłyszeć?',
        'Jak pachnie to miejsce?',
        'Jak wyglądałby tam poranek?',
        'Jak wyglądałby tam wieczór?',
        'Kto najczęściej mógłby tam przebywać?',
        'Jakie rzeczy są tam typowe?',
        'Czy jest tam bardziej słonecznie czy bardziej ciemno?',
        'Co byłoby tam najbardziej charakterystyczne?',
        'Jakie kolory dominują w tym miejscu?',
        'Jaki kolor może kojarzyć się z tym miejscem?',
        'Jakie rzeczy można tam robić?',
        'Jakie rzeczy byłyby tam zabronione lub dziwne?',
        'Jak wyglądałby krajobraz tego miejsca?',
        'Jakie jedzenie mogłoby się tam pojawić?',
        'Jakie ubrania pasują do tego miejsca?',
        'Jakie zwierzęta mogłyby tam żyć lub pasować?',
        'Jakie budynki lub struktury tam pasują?',
        'Jak duże jest to miejsce w twojej wyobraźni?',
        'Czy to miejsce jest bardziej spokojne czy chaotyczne?',
        'Czy to miejsce jest bardziej nowoczesne czy stare?',
        'Czy to miejsce jest bardziej naturalne czy stworzone przez człowieka?',
        'Jakie wydarzenia mogłyby się tam odbywać?',
        'Jakie historie mogłyby się tam wydarzyć?',
        'Jak ktoś czułby się w tym miejscu po 10 minutach?',
        'Jak ktoś czułby się w tym miejscu po 1 dniu?',
        'Jakie elementy najbardziej zapadają w pamięć?',
        'Co byłoby tam najbardziej niebezpieczne?',
        'Co byłoby tam najbardziej przyjazne?',
        'Jak wyglądałby widok z tego miejsca?',
        'Jak wyglądałoby to miejsce w nocy?',
        'Jak wyglądałoby to miejsce w różnych porach roku?',
        'Jakie historie mogliby opowiadać ludzie o tym miejscu?',
        'Jakie dźwięki dominują w tym miejscu?',
        'Czy to miejsce jest bardziej znane czy ukryte?',
        'Czy to miejsce jest bardziej publiczne czy prywatne?',
        'Jakie aktywności pasują do tego miejsca?',
        'Jakie rzeczy są tam normalne?',
        'Jakie wspomnienia mogłyby się z nim kojarzyć?',
        'Jak wyglądałby pierwszy raz w tym miejscu?',
        'Jak wyglądałoby opuszczenie tego miejsca?',
        'Jakie rzeczy definiują to miejsce w 1 zdaniu?',
        'Jakie słowo najlepiej opisuje klimat tego miejsca?',
        'Co zobaczyłbyś jako pierwsze po wejściu do tego miejsca?',
        'Jakie wrażenie sprawia to miejsce na pierwszy rzut oka?',
        'Co w tym miejscu mogłoby być ukryte przed większością osób?',
        'Jakie przedmioty byłyby tu porozrzucane lub obecne?',
        'Jakie przedmioty byłyby tu absolutnie nie na miejscu?',
        'Jak zmienia się zapach w zależności od pory dnia?',
        'Jakie dźwięki byłyby tu całkowicie nieoczekiwane?',
        'Jakie materiały dominują w strukturach tego miejsca?',
        'Jakie aktywności są tu najczęstsze w ciągu dnia?',
        'Co byłoby tutaj uznane za normalne zachowanie?',
        'Co mogłoby być zakazane w tym miejscu?',
        'Jakie emocje dominują u osób przebywających tutaj?',
        'Jakie elementy architektury są tu najbardziej charakterystyczne?',
        'Jakie kolory byłyby widoczne o zmierzchu?',
        'Jakie zwierzęta mogłyby się tu pojawiać?',
        'Jakie rośliny mogłyby tu rosnąć?',
        'Jakie ubrania byłyby tu całkowicie niepasujące?',
        'Jakie jedzenie może kojarzyć się z tym miejscem?',
        'Wymień jeden obiekt który może być użyty w tym miejscu',
        'Jakie obiekty są tu rzadko spotykane?',
        'Jakie interakcje między ludźmi są tu typowe?',
        'Jakie interakcje między ludźmi byłyby tu rzadkie?',
        'Jakie światło dominuje w tym miejscu (kolor, źródło)?',
        'Jakie przedmioty byłyby tu najcenniejsze?',
        'Jakie dźwięki natury mogłyby tu występować?',
        'Jakie emocje wywołuje pierwsza minuta w tym miejscu?',
        'Jakie elementy najbardziej przyciągają uwagę?',
        'Co mogłoby sprawić, że ktoś chciałby tu wrócić?',
        'Co mogłoby sprawić, że ktoś chciałby stąd uciec?',
        'Jakie osoby najlepiej odnajdują się w tym miejscu?',
        'Jakie osoby czułyby się tu niekomfortowo?',
        'Jakie jedno zdanie najlepiej oddaje istotę tego miejsca?'
      ]
    },
    {
      name: "Zwierzę", // 97 zwierząt, 99 pytań tak/nie, 65 pytań otwartych
      values: [
        'Lew',
        'Tygrys',
        'Lampart',
        'Jeleń',
        'Nosorożec',
        'Słoń',
        'Goryl',
        'Szympans',
        'Zebra',
        'Koala',
        'Kangur',
        'Panda',
        'Lama',
        'Surykatka',
        'Gepard',
        'Hiena',
        'Hipopotam',
        'Krokodyl',
        'Wieloryb',
        'Delfin',
        'Rekin',
        'Meduza',
        'Żółw',
        'Płaszczka',
        'Wiewiórka',
        'Niedźwiedź',
        'Wilk',
        'Lis',
        'Bóbr',
        'Jeż',
        'Sarna',
        'Żubr',
        'Krokodyl',
        'Baran',
        'Sowa',
        'Puchacz',
        'Orzeł',
        'Jaskółka',
        'Gołąb',
        'Papuga',
        'Kura',
        'Gęś',
        'Indyk',
        'Pies',
        'Kot',
        'Królik',
        'Chomik',
        'Żółw lądowy',
        'Świnka morska',
        'Koń',
        'Osioł',
        'Krowa',
        'Owca',
        'Koza',
        'Świnia',
        'Wół',
        'Kura',
        'Indyk',
        'Gęś',
        'Papuga',
        'Zając',
        'Niedźwiedź polarny',
        'Rysi',
        'Wydra',
        'Manat',
        'Słoń afrykański',
        'Wielbłąd',
        'Antylopa',
        'Puma',
        'Kuna',
        'Sokół',
        'Wrona',
        'Bąk',
        'Czapla',
        'Mewa',
        'Ryś',
        'Jeżozwierz',
        'Pelikany',
        'Wieloryb',
        'Narwal',
        'Foka',
        'Leniwiec',
        'Pangolin',
        'Kozica',
        'Kormoran',
        'Dzik',
        'Bóbr',
        'Lemur',
        'Maki',
        'Koczkodan',
        'Tarantula',
        'Gąsienica',
        'Motyl',
        'Ćma',
        'Mrówka',
        'Pchła',
        'Ślimak',
        'Raki',
      ],
      questionsYesNo: [
        'Czy to mieszka na lądzie?',
        'Czy to potrafi latać?',
        'Czy to potrafi pływać?',
        'Czy to żyje w Polsce?',
        'Czy to dzikie?',
        'Czy to domowe?',
        'Czy to jest duże?',
        'Czy to jest małe?',
        'Czy to ma futro?',
        'Czy to ma pióra?',
        'Czy to ma łuski?',
        'Czy to ma ogon?',
        'Czy to ma skrzydła?',
        'Czy to ma cztery nogi?',
        'Czy to jest niebezpieczne?',
        'Czy to może być jadowite?',
        'Czy to potrafi wspinać się po drzewach?',
        'Czy to je mięso?',
        'Czy to je rośliny?',
        'Czy to wszystkożerne?',
        'Czy to wydaje głośne dźwięki?',
        'Czy to szybkie?',
        'Czy to wolne?',
        'Czy to jest hodowane przez ludzi?',
        'Czy to zamieszkuje dżunglę?',
        'Czy to żyje na pustyni?',
        'Czy to żyje w morzu?',
        'Czy to żyje w rzece lub jeziorze?',
        'Czy to wspina się po górach?',
        'Czy to żyje w stadzie?',
        'Czy to żyje samotnie?',
        'Czy to lubi ludzi?',
        'Czy to występuje w ogrodzie zoologicznym?',
        'Czy to jest zagrożone wyginięciem?',
        'Czy to śpi w nocy?',
        'Czy to aktywne jest w dzień?',
        'Czy to zapada w sen zimowy?',
        'Czy to potrafi skakać?',
        'Czy to umie nurkować?',
        'Czy to jest ssakiem?',
        'Czy to jest gadem?',
        'Czy to jest ptakiem?',
        'Czy to jest rybą?',
        'Czy to jest płazem?',
        'Czy to jest owadem?',
        'Czy to mieszka pod ziemią?',
        'Czy to kopie nory?',
        'Czy to ma długą szyję?',
        'Czy to ma rogi?',
        'Czy to ma kły?',
        'Czy to ma pazury?',
        'Czy to ma skrzela?',
        'Czy to jest kolorowe?',
        'Czy to zmienia kolor?',
        'Czy to potrafi udawać martwe?',
        'Czy to lata naprawdę wysoko?',
        'Czy to szybko rośnie?',
        'Czy to żyje bardzo długo?',
        'Czy to może być trzymane w akwarium?',
        'Czy to żyje w stadninie, gospodarstwie lub zagrodzie?',
        'Czy to żyje tylko w jednym kraju lub regionie?',
        'Czy to potrafi mówić lub naśladować głosy?',
        'Czy to poluje?',
        'Czy to potrafi się bronić kolcami?',
        'Czy to potrafi pływać pod lodem?',
        'Czy to lubi ciepło?',
        'Czy to wytrzymuje bardzo niskie temperatury?',
        'Czy to jest silne?',
        'Czy to potrafi przynosić szczęście w wierzeniach ludzi?',
        'Czy to można głaskać?',
        'Czy to ma długie uszy?',
        'Czy to ma długi ogon?',
        'Czy to potrafi gryźć mocno?',
        'Czy to potrafi żyć w mieście?',
        'Czy to jest znane z bajek?',
        'Czy to występuje na sawannie?',
        'Czy to potrafi kopać bardzo szybko?',
        'Czy to jest śliskie?',
        'Czy to buduje gniazda?',
        'Czy to potrafi żuć przez długi czas?',
        'Czy to świetnie widzi w nocy?',
        'Czy to ma ostre zęby?',
        'Czy to jest szybkie w wodzie?',
        'Czy to wydaje nieprzyjemny zapach?',
        'Czy to potrafi głośno ryczeć, wyć lub wrzeszczeć?',
        'Czy to potrafi spać na drzewie?',
        'Czy to jest miękkie w dotyku?',
        'Czy to może przenosić choroby?',
        'Czy to uważane jest za słodkie?',
        'Czy to może być bohaterem filmu animowanego?',
        'Czy to potrafi oddychać pod wodą?',
        'Czy to ma długie włosy lub sierść?',
        'Czy to umie chodzić po dwóch nogach?',
        'Czy to często występuje w książkach dla dzieci?',
        'Czy to wchodzi do domów ludzi?',
        'Czy to wydaje jakieś znane charakterystyczne dźwięki?',
        'Czy to bardzo szybko biega?',
        'Czy to jest ciężkie?',
        'Czy to lubi się bawić?',
        'Czy to czasem udaje, że jest martwe?'
      ],
      questionsOpen: [
        'Jakie dwa słowa mogą kojarzyć się z tym zwierzęciem?',
        'Jakie słowo może kojarzyć się z tym zwierzęciem?',
        'Jaki kolor może kojarzyć się z tym zwierzęciem?',
        'Jaki kraj może kojarzyć się z tym zwierzęciem?',
        'Jaki przedmiot domowy może kojarzyć się z tym zwierzęciem?',
        'Jak wygląda typowy dzień tego zwierzęcia?',
        'Gdzie najczęściej można je spotkać?',
        'Jakie 2 rzeczy najbardziej się z nim kojarzą?',
        'Jakie dźwięki wydaje to zwierzę?',
        'Pokaż jak to zwierzę porusza się na co dzień?',
        'Jakie środowisko naturalne mu odpowiada?',
        'Jakie jedzenie najbardziej z nim się kojarzy?',
        'Czy to zwierzę jest bardziej groźne czy łagodne?',
        'Jakie emocje budzi to zwierzę?',
        'Jak wyglądałoby to zwierzę w bajce?',
        'Jakie zwierzę najbardziej przypomina charakterem?',
        'Jakie 2 przymiotniki najlepiej je opisują?',
        'Jakie ma naturalne „supermoce” (cechy)?',
        'Jak się zachowuje wobec ludzi?',
        'Jak się zachowuje wobec innych zwierząt?',
        'Czy to zwierzę żyje samotnie czy w grupie?',
        'Jak wygląda jego typowe schronienie?',
        'Jakie warunki pogodowe lubi najbardziej?',
        'Jakie warunki są dla niego trudne?',
        'Jak wygląda jego „dzień z życia”?',
        'Co to zwierzę robi, gdy się boi?',
        'Co to zwierzę robi, gdy jest spokojne?',
        'Jak to zwierzę zdobywa jedzenie?',
        'Jakie jest jego największe zagrożenie?',
        'Jakie jest jego największe „atuty”?',
        'Jakie dźwięki kojarzą się z jego obecnością?',
        'Jakie miejsca odwiedza najczęściej?',
        'Jakie zapachy mogłyby się z nim kojarzyć?',
        'Jak reaguje na zagrożenie?',
        'Jak reaguje na człowieka?',
        'Jakie ma typowe zachowania?',
        'Czy to zwierzę jest szybkie czy wolne?',
        'Czy to zwierzę jest duże czy małe?',
        'Czy to zwierzę jest bardziej dzikie czy oswojone?',
        'Jakie cechy czynią je wyjątkowym?',
        'Jakie miejsce najlepiej pasuje do tego zwierzęcia?',
        'Jakie słowo najlepiej je opisuje?',
        'Jaki film, bajka lub książka mogą kojarzyć się z tym zwierzęciem?',
        'Jaka pora dnia najbardziej pasuje do tego zwierzęcia?',
        'Jaki zawód najlepiej pasowałby temu zwierzęciu?',
        'Do jakiego gatunku filmu pasowałoby to zwierzę?',
        'Jaka pogoda najlepiej oddaje charakter tego zwierzęcia?',
        'Jaka faktura lub materiał kojarzy się z tym zwierzęciem?',
        'Jaka roślina najlepiej pasuje do tego zwierzęcia?',
        'Który zmysł jest u niego najsilniejszy?',
        'Co to zwierzę zawsze miałoby przy sobie w plecaku?',
        'W jakiej dyscyplinie sportu miałoby największe szanse?',
        'Jakie imię najbardziej pasuje do tego zwierzęcia?',
        'Jaką część domu najbardziej polubiłoby to zwierzę?',
        'Jakie miejsce na mapie świata najbardziej do niego pasuje?',
        'Z jaką grą komputerową może kojarzyć sie to zwierzę?',
        'Jakie trzy rzeczy zabrałoby na bezludną wyspę?',
        'Jakie ubranie nosiłoby najczęściej?',
        'Jakie miejsce w lesie wybrałoby na bazę?',
        'Jaką temperaturę uznałoby za idealną?',
        'Jaką przeszkodę pokonałoby bez trudu?',
        'Jaką strategię wybiera: cierpliwość czy spontaniczność?',
        'Jaka umiejętność przydałaby się temu zwierzęciu?',
        'Jakie warunki sprawiają, że to zwierzę czuje się pewnie?',
        'Jakie warunki sprawiają, że staje się ostrożne?',
        'Jakie słowo najgorzej opisuje to zwierzę?'
      ]
    },
    {
      name: "Przedmiot", // 150 przedmiotów, 145 pytań tak/nie, 80 pytań otwartych
      values: [
        'Laptop',
        'Telefon',
        'Telewizor',
        'Książka',
        'Długopis',
        'Ołówek',
        'Notatnik',
        'Czajnik',
        'Zegarek',
        'Kamera',
        'Słuchawki',
        'Myszka komputerowa',
        'Klawiatura',
        'Drukarka',
        'Lampka biurkowa',
        'Chlebak',
        'Mikrofalówka',
        'Kuchnia',
        'Lodówka',
        'Zmywarka',
        'Ekspres do kawy',
        'Czajnik elektryczny',
        'Toster',
        'Deska do krojenia',
        'Garnek',
        'Patelnia',
        'Szczoteczka do zębów',
        'Szczotka do włosów',
        'Ręcznik',
        'Poduszka',
        'Kołdra',
        'Zasłony',
        'Rama zdjęciowa',
        'Mop',
        'Odkurzacz',
        'Pralka',
        'Suszarka do włosów',
        'Żelazko',
        'Wieszak',
        'Kubek',
        'Talerz',
        'Sztućce',
        'Butelka',
        'Wazon',
        'Świeczka',
        'Zapałki',
        'Papier toaletowy',
        'Ścierka',
        'Myjka do naczyń',
        'Worek na śmieci',
        'Skrzynka na narzędzia',
        'Narzędzia',
        'Wkrętarka',
        'Wiertarka',
        'Młotek',
        'Śrubokręt',
        'Klej',
        'Szczypce',
        'Miarka',
        'Termometr',
        'Lustro',
        'Rama obrazu',
        'Kalendarz',
        'Agrafki',
        'Spinacz',
        'Koperta',
        'Zszywacz',
        'Gumki recepturki',
        'Tablica korkowa',
        'Fotel',
        'Stół',
        'Krzesło',
        'Szafa',
        'Komoda',
        'Stolik kawowy',
        'Regał',
        'Lampa stojąca',
        'Podgrzewacz do filiżanek',
        'Zestaw do herbaty',
        'Waga kuchenna',
        'Tarka',
        'Sitko',
        'Mieszadło',
        'Frytkownica',
        'Sokowirówka',
        'Grill',
        'Lodówka',
        'Wagonik',
        'Klepsydra',
        'Skrzynka na listy',
        'Skrzynia',
        'Tablica do rysowania',
        'Płytki CD',
        'Głośnik',
        'Mikrofon',
        'Lampka nocna',
        'Zegarek ścienny',
        'Torba',
        'Plecak',
        'Portfel',
        'Parasol',
        'Okulary',
        'Latarka',
        'Powerbank',
        'Pilot',
        'Router',
        'Pendrive',
        'Dysk zewnętrzny',
        'Ładowarka',
        'Bateria',
        'Kalkulator',
        'Nożyczki',
        'Taśma klejąca',
        'Linijka',
        'Pędzel',
        'Farby',
        'Piórnik',
        'Segregator',
        'Dziurkacz',
        'Notes samoprzylepny',
        'Walizka',
        'Bidon',
        'Termos',
        'Koc',
        'Budzik',
        'Wentylator',
        'Grzejnik',
        'Nawilżacz powietrza',
        'Oczyszczacz powietrza',
        'Doniczka',
        'Konewka',
        'Leżak',
        'Hamak',
        'Drabina',
        'Skakanka',
        'Piłka',
        'Hulajnoga',
        'Rower',
        'Kask',
        'Gitara',
        'Puzzle',
        'Klocki',
        'Szachy',
        'Talia kart',
        'Jojo',
        'Maskotka',
        'Lornetka',
        'Kompas',
        'Apteczka',
        'Śpiwór',
      ],
      questionsYesNo: [
        'Czy to można z łatwością przenieść?',
        'Czy to działa na prąd?',
        'Czy to można znaleźć w każdym domu?',
        'Czy to jest większe od Twojej głowy?',
        'Czy to używane jest codziennie?',
        'Czy to robi hałas?',
        'Czy to kosztuje dużo pieniędzy?',
        'Czy to można znaleźć w szkole?',
        'Czy to służy do pisania?',
        'Czy to ma ekran?',
        'Czy to jest elektroniczne?',
        'Czy to może się zepsuć?',
        'Czy to ma kółka?',
        'Czy to służy do krojenia?',
        'Czy to znajduje się zwykle w kuchni?',
        'Czy to można kupić w supermarkecie?',
        'Czy dzieci często tego używają?',
        'Czy to mieści się w kieszeni?',
        'Czy to jest miękkie?',
        'Czy to jest twarde?',
        'Czy tym można rzucić?',
        'Czy to ma baterie?',
        'Czy to służy do sprzątania?',
        'Czy to można założyć na siebie?',
        'Czy to jest potrzebne do pracy?',
        'Czy to służy do rozrywki?',
        'Czy to można powiesić na ścianie?',
        'Czy to jest okrągłe?',
        'Czy to wykonane jest z plastiku?',
        'Czy to wykonane jest z drewna?',
        'Czy to szybko się zużywa?',
        'Czy to służy do jedzenia lub picia?',
        'Czy tym można mierzyć?',
        'Czy to ma przyciski?',
        'Czy to może być niebezpieczne?',
        'Czy tym można sterować?',
        'Czy można to pożyczyć od kogoś?',
        'Czy to służy do komunikacji?',
        'Czy to ma mechanizm w środku?',
        'Czy to daje się komuś w prezencie?',
        'Czy to jest kolorowe?',
        'Czy to nosi się na ręce?',
        'Czy to generuje ciepło?',
        'Czy to można złożyć lub rozłożyć?',
        'Czy to można zapalić?',
        'Czy to służy do rysowania?',
        'Czy to łatwo złamać?',
        'Czy to ma kabel?',
        'Czy to używane jest na dworze?',
        'Czy to może być bardzo małe?',
        'Czy to można podłączyć do internetu?',
        'Czy to potrzebne jest do gotowania?',
        'Czy to można kupić online?',
        'Czy to znajduje się w szpitalu?',
        'Czy to używane jest w samochodzie?',
        'Czy to nosi się przy sobie?',
        'Czy to służy do sportu?',
        'Czy to może być dekoracją?',
        'Czy to świeci?',
        'Czy tym można otwierać inne rzeczy?',
        'Czy to pomaga dbać o higienę?',
        'Czy to używane jest w biurze?',
        'Czy to ma w środku płyn?',
        'Czy to można postawić na półce?',
        'Czy to ma koła?',
        'Czy to trzeba często ładować?',
        'Czy to można łatwo zgubić?',
        'Czy to jest delikatne?',
        'Czy to wydaje dźwięki?',
        'Czy tym można coś naprawić?',
        'Czy to używane jest do nauki?',
        'Czy to składa się z części?',
        'Czy to wymaga instrukcji obsługi?',
        'Czy to chroni przed zimnem lub deszczem?',
        'Czy to można personalizować?',
        'Czy to ma przód i tył?',
        'Czy to jest wykonane z metalu?',
        'Czy to ma pokrywkę?',
        'Czy to można otwierać i zamykać?',
        'Czy to jest głównie dla dorosłych?',
        'Czy tym można coś dziurawić lub ciąć?',
        'Czy to ma ekran dotykowy?',
        'Czy w tym można coś przechowywać?',
        'Czy to pomaga w podróży?',
        'Czy to jest dostępne tylko w specjalnych sklepach?',
        'Czy to można przytulić?',
        'Czy to jest gładkie?',
        'Czy to ma ostrze?',
        'Czy to służy do odtwarzania muzyki?',
        'Czy to może latać?',
        'Czy to może samo się poruszać?',
        'Czy tym można pisać lub rysować?',
        'Czy to może mieć koła albo narty?',
        'Czy to ma sznurek, pasek albo taśmę?',
        'Czy na tym są litery lub symbole?',
        'Czy to jest wodoodporne?',
        'Czy to pomaga w czasie choroby?',
        'Czy to może być zdalnie sterowane?',
        'Czy to może zmieniać kształt?',
        'Czy to służy do zabawy?',
        'Czy to może być bardzo stare lub zabytkowe?',
        'Czy to jest cięższe niż kilogram?',
        'Czy to można trzymać jedną ręką?',
        'Czy to zmieści się w plecaku?',
        'Czy to można kupić na stacji benzynowej?',
        'Czy to występuje w różnych rozmiarach?',
        'Czy to występuje w różnych kolorach?',
        'Czy to ma uchwyt?',
        'Czy to ma zamek błyskawiczny?',
        'Czy to ma pokrywę lub klapkę?',
        'Czy to ma wymienne części?',
        'Czy to wymaga konserwacji?',
        'Czy to trzeba regularnie czyścić?',
        'Czy to może się stłuc?',
        'Czy to może rdzewieć?',
        'Czy to może się zagiąć?',
        'Czy to można złożyć na płasko?',
        'Czy to można schować do szuflady?',
        'Czy to można nosić w torbie?',
        'Czy to ma logo lub markę?',
        'Czy to jest sprzedawane w zestawach?',
        'Czy to może być jednorazowe?',
        'Czy to może być wielokrotnego użytku?',
        'Czy to można myć w zmywarce?',
        'Czy to może być wykonane ze szkła?',
        'Czy to ma gumowe elementy?',
        'Czy to ma ruchome części?',
        'Czy to wymaga montażu?',
        'Czy to można postawić na stole?',
        'Czy to używane jest głównie przez jedną osobę?',
        'Czy z tego korzysta się w nocy?',
        'Czy to przydaje się podczas wakacji?',
        'Czy to często zabiera się w podróż?',
        'Czy to można znaleźć w hotelu?',
        'Czy to używane jest w łazience?',
        'Czy to można kupić w aptece?',
        'Czy to może być kolekcjonowane?',
        'Czy to może mieć wartość sentymentalną?',
        'Czy to może być wykonane ręcznie?',
        'Czy to jest używane sezonowo?',
        'Czy to może służyć więcej niż do jednego celu?',
        'Czy to może wymagać baterii lub ładowania?',
        'Czy to może działać bez prądu?',
        'Czy to można naprawić samodzielnie?',
        'Czy to może zawierać instrukcję lub etykietę?'
      ],
      questionsOpen: [
        'Do czego służy ten przedmiot?',
        'Z jakim innym przedmiotem może kojarzyć się ten przedmiot?',
        'Z jakim kolorem może kojarzyć się ten przedmiot?',
        'Jakie 2 przymiotniki opisują ten przedmiot?',
        'Czy masz jakieś skojarzenia z tym przedmiotem?',
        'Czy masz jakieś wspomnienia z tym przedmiotem?',
        'Kto najczęściej go używa?',
        'Gdzie można go znaleźć na co dzień?',
        'Z jaką sytuacją najbardziej się kojarzy?',
        'Jak wygląda moment użycia tego przedmiotu?',
        'Jakie 2 rzeczy najbardziej się z nim kojarzą?',
        'Jakie słowo może kojarzyć sie z tym przedmiotem?',
        'Jak wyglądałby jego typowy użytkownik?',
        'W jakich miejscach ten przedmiot jest najbardziej potrzebny?',
        'Co by się stało, gdyby nagle go zabrakło?',
        'Jakie ma najważniejsze cechy?',
        'Co jest w nim najważniejsze: wygląd, funkcja czy wygoda?',
        'Jak wyglądałby jego „dzień pracy”, gdyby był żywy?',
        'Z czym najczęściej się go myli?',
        'Jakie inne przedmioty są do niego podobne?',
        'Co jest jego największą zaletą?',
        'Co jest jego największą wadą?',
        'Jakie problemy rozwiązuje ten przedmiot?',
        'Jakie problemy może powodować?',
        'Jak wyglądałby w bardzo dużej wersji?',
        'Jak wyglądałby w miniaturowej wersji?',
        'Jakie emocje może wywoływać jego użycie?',
        'Jak brzmi moment jego używania (dźwięk)?',
        'Jak pachnie w jego otoczeniu?',
        'Jak wygląda jego typowe miejsce przechowywania?',
        'Jak często ludzie z niego korzystają?',
        'Czy jest to przedmiot codzienny czy specjalistyczny?',
        'Czy jest to przedmiot prosty czy skomplikowany?',
        'Jak wyglądałby w przeszłości (100 lat temu)?',
        'Jak wyglądałby w przyszłości?',
        'Jakie materiały są z nim kojarzone?',
        'Jakie kolory najczęściej go opisują?',
        'Jakie rzeczy robią ludzie przed jego użyciem?',
        'Jakie rzeczy robią ludzie po jego użyciu?',
        'Jakie sytuacje „wymuszają” jego użycie?',
        'Jakie alternatywy istnieją dla tego przedmiotu?',
        'Co czyni go wyjątkowym na tle innych?',
        'Jak wyglądałby jego zepsuty wariant?',
        'Jakie dźwięki lub ruchy są z nim związane?',
        'Jak wyglądałby jako element filmu lub gry?',
        'Jakie historie mogłyby się z nim wiązać?',
        'Jakie słowo najlepiej go opisuje?',
        'Jakie miejsce najlepiej pasuje do tego przedmiotu?',
        'Jakie rzeczy ludzie robią z nim nieprawidłowo?',
        'Jakie jest jego najczęstsze zastosowanie?',
        'Jakie jest jego najmniej oczywiste zastosowanie?',
        'Jak wyglądałby jego „idealny użytkownik”?',
        'Jak wyglądałby jego „katastrofalny scenariusz użycia”?',
        'Jakie uczucie daje jego posiadanie?',
        'Jaką jedną scenę najlepiej z nim kojarzysz?',
        'Jaką czynność najbardziej ułatwia ten przedmiot?',
        'Jaka osoba najbardziej by za nim tęskniła?',
        'W jakim pomieszczeniu najtrudniej byłoby się bez niego obejść?',
        'O jakiej porze dnia najczęściej się go używa?',
        'Z jaką porą roku najbardziej się kojarzy?',
        'W jakim wieku ludzie zaczynają go używać?',
        'Jakie dwa słowa widniałyby w jego reklamie?',
        'Jak wyglądałoby opakowanie tego przedmiotu?',
        'Jakiego materiału zdecydowanie nie znajdziesz w tym przedmiocie?',
        'Jakie miejsce byłoby najgorsze do używania tego przedmiotu?',
        'W jakiej pracy ten przedmiot jest szczególnie ważny?',
        'Jak wyglądałby świat bez tego przedmiotu?',
        'Jakie inne przedmioty zwykle znajdują się obok niego?',
        'Jak można go wykorzystać w nietypowy sposób?',
        'Co najczęściej się w nim psuje?',
        'Jak można poznać, że jest dobrej jakości?',
        'Po czym poznasz, że trzeba go wymienić na nowy?',
        'Jaką jedną rzecz zmieniłbyś w tym przedmiocie?',
        'Jakie miejsce w domu najbardziej do niego pasuje?',
        'Jakie miejsce poza domem najbardziej do niego pasuje?',
        'Jaki zawód kojarzy się z tym przedmiotem?',
        'Jakie wspomnienie z dzieciństwa może się z nim wiązać?',
        'Jaki zapach najlepiej do niego pasuje?',
        'Jakie miejsce byłoby dla niego najbardziej niebezpieczne?',
        'Co najbardziej zaskakuje ludzi w tym przedmiocie?'
      ]
    },
    {
      name: "Jedzenie", // 150 jedzeń, 128 pytań tak/nie, 75 pytań otwartych
      values: [
        'Kotlet schabowy',
        'Bigos',
        'Pierogi ruskie',
        'Zupa pomidorowa',
        'Rosół',
        'Gołąbki',
        'Barszcz czerwony',
        'Żurek',
        'Kebab',
        'Pizza Margherita',
        'Spaghetti Bolognese',
        'Lasagne',
        'Tiramisu',
        'Burger z wołowiną',
        'Frytki',
        'Hot dog',
        'Kurczak z rożna',
        'Jajecznica',
        'Omlet',
        'Kiełbasa biała',
        'Sernik',
        'Szarlotka',
        'Lody czekoladowe',
        'Pączki z marmoladą',
        'Kawa espresso',
        'Czekolada z orzechami',
        'Chleb',
        'Bagietka',
        'Rogal',
        'Croissant',
        'Baton Snickers',
        'Baton Mars',
        'Baton Twix',
        'Baton Milky Way',
        'Chipsy Lays',
        'Chipsy Pringles',
        'Orzeszki ziemne',
        'Pistacje',
        'Migdały',
        'Banan',
        'Jabłko',
        'Gruszka',
        'Pomarańcza',
        'Mandarynka',
        'Truskawka',
        'Malina',
        'Borówka amerykańska',
        'Winogrona',
        'Morela',
        'Śliwka',
        'Ananas',
        'Mango',
        'Awokado',
        'Sałatka cezar',
        'Tarta owocowa',
        'Makaron spaghetti',
        'Tortilla',
        'Burrito',
        'Quesadilla',
        'Nachos',
        'Guacamole',
        'Sushi',
        'Tatar wołowy',
        'Sznycel wiedeński',
        'Krewetki',
        'Tuńczyk w sosie własnym',
        'Tosty z szynką',
        'Jajko sadzone',
        'Ryż biały',
        'Sos sojowy',
        'Sos BBQ',
        'Sos czosnkowy',
        'Majonez',
        'Ketchup',
        'Musztarda',
        'Chrzan',
        'Hummus',
        'Baklava',
        'Kawałek tortu czekoladowego',
        'Ciasto marchewkowe',
        'Muffiny czekoladowe',
        'Rogal z dżemem',
        'Kanapka z szynką',
        'Masło orzechowe',
        'Dżem truskawkowy',
        'Nutella',
        'Miód',
        'Chałwa',
        'Beza',
        'Ciasteczka owsiane',
        'Ciasteczka czekoladowe',
        'Galaretka owocowa',
        'Kisiel truskawkowy',
        'Budyń waniliowy',
        'Pieczony ziemniak',
        'Kapusta kiszona',
        'Ogórek kiszony',
        'Marynowane grzyby',
        'Piernik',        
        'Placki ziemniaczane',
        'Naleśniki z serem',
        'Kopytka',
        'Pyzy',
        'Kluski śląskie',
        'Fasolka po bretońsku',
        'Grochówka',
        'Zupa ogórkowa',
        'Krupnik',
        'Flaki',
        'Kotlet mielony',
        'Devolay',
        'Gulasz wołowy',
        'Pieczeń rzymska',
        'Łosoś pieczony',
        'Paluszki rybne',
        'Zapiekanka',
        'Tost francuski',
        'Owsianka',
        'Musli',
        'Jogurt naturalny',
        'Twarożek',
        'Mozzarella',
        'Camembert',
        'Parmezan',
        'Tofu',
        'Falafel',
        'Ramen',
        'Pad Thai',
        'Curry z kurczakiem',
        'Paella',
        'Risotto',
        'Gnocchi',
        'Bruschetta',
        'Carpaccio',
        'Sałatka grecka',
        'Sałatka jarzynowa',
        'Wrap z kurczakiem',
        'Focaccia',
        'Bagel',
        'Donut',
        'Wafle ryżowe',
        'Popcorn',
        'Żelki owocowe',
        'Krakersy',
        'Prażona kukurydza',
        'Kiwi',
        'Arbuz',
        'Granat',
        'Kokos',
        'Smalec',
      ],
      questionsYesNo: [
        'Czy to danie jest słodkie?',
        'Czy można to zjeść na śniadanie?',
        'Czy jada się to na ciepło?',
        'Czy potrzebny jest widelec?',
        'Czy ma to mięso?',
        'Czy pochodzi z Polski?',
        'Czy to jest danie wegetariańskie?',
        'Czy to coś płynnego?',
        'Czy to jada się rękami?',
        'Czy można to kupić w fast foodzie?',
        'Czy jest chrupiące?',
        'Czy to popularne na święta?',
        'Czy to można wypić?',
        'Czy wymaga pieczenia?',
        'Czy to jest nabiał?',
        'Czy to jest danie obiadowe?',
        'Czy to ma dużo kalorii?',
        'Czy jest ostre?',
        'Czy to deser?',
        'Czy to ma jakiś sos?',
        'Czy pochodzi z Włoch?',
        'Czy można to zjeść w kinie?',
        'Czy to jest owoc?',
        'Czy to ma skórkę?',
        'Czy to coś słonego?',
        'Czy to da się rozsmarować?',
        'Czy trzeba to kroić?',
        'Czy to da się zrobić w domu bez przepisu?',
        'Czy to ma dziwny zapach?',
        'Czy to jest zdrowe?',
        'Czy dzieci to lubią?',
        'Czy to wymaga lodówki?',
        'Czy można to grillować?',
        'Czy to jest smażone?',
        'Czy to ma dużo cukru?',
        'Czy to się długo gotuje?',
        'Czy to jest tradycyjne danie?',
        'Czy to można zabrać na piknik?',
        'Czy to coś, co można zjeść w biegu?',
        'Czy to ma nadzienie?',
        'Czy to się lepi?',
        'Czy to ma sery?',
        'Czy to widać często na reklamach?',
        'Czy można to dać jako prezent?',
        'Czy to jest egzotyczne?',
        'Czy to ma skorupę?',
        'Czy to wymaga łyżki?',
        'Czy to często pojawia się w diecie sportowców?',
        'Czy to jest chrupkie na zewnątrz i miękkie w środku?',
        'Czy to trzeba przeżuwać długo?',
        'Czy to nadaje się dla wegan?',
        'Czy łatwo tym ubrudzić ubranie?',
        'Czy są różne smaki tej rzeczy?',
        'Czy to można mrozić?',
        'Czy to jest szybkie w przygotowaniu?',
        'Czy jada się to w weekendy częściej niż w tygodniu?',
        'Czy to można posolić?',
        'Czy to jada się z czymś jeszcze?',
        'Czy to danie ma sos pomidorowy?',
        'Czy to jest typowa przekąska?',
        'Czy to jest drogie?',
        'Czy to jada się na zimno?',
        'Czy to tradycja jakaś narodowa?',
        'Czy to robi się z mąki?',
        'Czy to jest płaskie?',
        'Czy to potrawa jednogarnkowa?',
        'Czy można się tym łatwo najeść?',
        'Czy to potrafi być ostre?',
        'Czy to może być w puszce?',
        'Czy to jest ulubione danie wielu ludzi?',
        'Czy to jest w restauracjach typu premium?',
        'Czy to ma sos serowy?',
        'Czy to jest suche?',
        'Czy trzeba to obrać?',
        'Czy to danie jest zupy?',
        'Czy to można pieprzyć?',
        'Czy to jest typowe na imprezach?',
        'Czy to ma dużo składników?',
        'Czy potrzebny jest nóż?',
        'Czy to można zrobić z resztek?',
        'Czy to danie jest kolorowe?',
        'Czy to pochodzi z Azji?',
        'Czy to jest sezonowe?',
        'Czy to ma pestki?',
        'Czy to można przełamać na pół?',
        'Czy to robią z ziemniaków?',
        'Czy to jest puszyste?',
        'Czy to jest tłuste?',
        'Czy to bywa panierowane?',
        'Czy można to wycisnąć?',
        'Czy to ma intensywny zapach?',
        'Czy to jest bardzo słone?',
        'Czy to podaje się na talerzu?',
        'Czy to ma określony kształt?',
        'Czy to jest danie typowe dla dzieci?',
        'Czy można to kupić w automacie?',
        'Czy to pasuje do kawy?',
        'Czy to często jada się z ketchupem?',
        'Czy to jest modne jedzenie?',
        'Czy to potrawa, którą łatwo przypalić?',
        'Czy to jedzenie często podaje się na przyjęciach?',
        'Czy to można podawać z ryżem?',
        'Czy to typowe jedzenie uliczne?',
        'Czy to jedzenie bywa bardzo ostre?',
        'Czy to potrawa, którą można zabrać do lunchboxa?',
        'Czy to jedzenie można dodać do sałatki?',
        'Czy to produkt mleczny?',
        'Czy to coś, co rośnie na drzewach?',
        'Czy to jedzenie często jada się w piątki?',
        'Czy to da się zrobić z ciasta?',
        'Czy to jedzenie jest narodowym symbolem jakiegoś kraju?',
        'Czy to potrawa, którą można smażyć na głębokim oleju?',
        'Czy to jedzenie jada się z masłem?',
        'Czy to jedzenie jada się w kilku warstwach?',
        'Czy to produkt mrożony?',
        'Czy to jedzenie wymaga obierania nożem?',
        'Czy można to przygotować w mikrofalówce?',
        'Czy to jedzenie można łatwo przewozić?',
        'Czy to jedzenie często je się na ulicy lub w podróży?',
        'Czy to może być składnik pizzy?',
        'Czy to jedzenie szybko traci świeżość?',
        'Czy to potrawa, którą je się zwykle widelcem i nożem razem?',
        'Czy to jedzenie często kupuje się na wynos?',
        'Czy to coś, co dzieci często proszą w restauracji?',
        'Czy to jedzenie łatwo rozpoznać po zapachu?',
        'Czy to jedzenie można posypać cukrem lub solą?',
        'Czy to może być zielone?',
        'Czy ktoś, kto jest uczulony, musi uważać na ten produkt?'
      ],
      questionsOpen: [
        'Jak smakuje to jedzenie (ogólny opis)?',
        'Z czym najbardziej się kojarzy to jedzenie?',
        'Z jakim kolorem kojarzy się to jedzenie?',
        'W jakiej sytuacji najczęściej się je je?',
        'Jak pachnie to jedzenie?',
        'Jak wygląda jego idealna wersja?',
        'Jak wygląda jego najgorsza wersja?',
        'Czy to jedzenie jest bardziej słodkie czy słone?',
        'Czy to jedzenie jest bardziej daniem czy przekąską?',
        'Gdzie najczęściej można je dostać?',
        'Kto najczęściej je je?',
        'Jakie emocje wywołuje to jedzenie?',
        'Jak wygląda moment jedzenia tego?',
        'Jakie 2 rzeczy najbardziej się z nim kojarzą?',
        'Jaką porę dnia najbardziej pasuje do tego jedzenia?',
        'Czy to jedzenie jest bardziej domowe czy restauracyjne?',
        'Czy to jedzenie jest bardziej proste czy skomplikowane?',
        'Jak wygląda jego tekstura?',
        'Jakie składniki mogą się w nim znajdować?',
        'Co sprawia, że to jedzenie jest wyjątkowe?',
        'Jakie jedzenie jest do niego podobne?',
        'Z jakiego kraju lub kultury może pochodzić?',
        'Jak wyglądałoby to jedzenie w wersji luksusowej?',
        'Jak wyglądałoby to jedzenie w wersji taniej?',
        'Jak wyglądałoby to jedzenie w wersji „fast food”?',
        'Jak wyglądałby zapach tego jedzenia w restauracji?',
        'Jak reagują ludzie, gdy je widzą?',
        'Jak reagują ludzie, gdy je jedzą po raz pierwszy?',
        'Jakie sytuacje są idealne do jedzenia tego?',
        'Jakie sytuacje są dziwne do jedzenia tego?',
        'Jakie napoje pasują do tego jedzenia?',
        'Jakie dodatki pasują do tego jedzenia?',
        'Jakie kolory kojarzą się z tym jedzeniem?',
        'Jak wygląda jego wersja domowa?',
        'Jak wygląda jego wersja restauracyjna?',
        'Jak wygląda jego wersja uliczna (street food)?',
        'Jakie wspomnienia mogą się z nim kojarzyć?',
        'Jakie jedzenie jest jego przeciwieństwem?',
        'Jakie jedzenie jest jego „najbliższym kuzynem”?',
        'Jakie dźwięki kojarzą się z jego jedzeniem (np. chrupanie)?',
        'Jak długo się je przygotowuje?',
        'Jak trudno jest je zrobić?',
        'Czy to jedzenie jest zdrowe czy niezdrowe?',
        'Jak wyglądałoby to jedzenie w kosmosie?',
        'Jak wyglądałoby to jedzenie w wersji dziecięcej?',
        'Jak wyglądałoby to jedzenie jako gigantyczne danie?',
        'Jak wyglądałoby to jedzenie jako mini wersja?',
        'Jakie słowo najlepiej je opisuje?',
        'Jaką jedną scenę najlepiej z nim kojarzysz?',
        'Jakie składniki są absolutnie kluczowe w tym jedzeniu?',
        'Co by się stało, gdyby zabrakło jednego składnika?',
        'Co jest w nim najbardziej „charakterystyczne” na języku?',
        'Jakie przyprawy najbardziej do niego pasują?',
        'Jakie przyprawy kompletnie do niego nie pasują?',
        'Jak wyglądałoby to jedzenie w wersji fit?',
        'Jak wyglądałoby to jedzenie w wersji deserowej?',
        'Jak wyglądałoby to jedzenie po 24 godzinach od przygotowania?',
        'Co najczęściej zostaje na talerzu po zjedzeniu?',
        'Co w tym jedzeniu najbardziej brudzi ręce lub talerz?',
        'Jakie sztućce są potrzebne do jedzenia tego?',
        'Czy można je jeść rękami?',
        'Jak wygląda jego typowa porcja?',
        'Czy łatwo przesadzić z ilością tego jedzenia?',
        'Jakie dodatki mogą całkowicie zmienić jego smak?',
        'Jakie dodatki są klasyczne?',
        'Jakie dodatki są nietypowe?',
        'Jakie wspomnienie z dzieciństwa może z nim się wiązać?',
        'Jakie miejsce najlepiej pasuje do jego jedzenia?',
        'Jakie miejsce jest absolutnie niepasujące do jego jedzenia?',
        'Jakie dźwięki wydaje podczas przygotowania?',
        'Jakie dźwięki wydaje podczas jedzenia?',
        'Co może pójść nie tak podczas robienia go?',
        'Jakie emocje wywołuje jego zapach?',
        'Jakie emocje wywołuje jego wygląd przed jedzeniem?',
        'Jakie napoje pasują do tego jedzenia?'
      ]
    }
  ]
}